// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Jul 15 16:21:22 2010

#include "dynBasePanelUI.h"

// begin wxGlade: ::extracode

// end wxGlade


dynBasePanelUI::dynBasePanelUI(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: dynBasePanelUI::dynBasePanelUI
    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(dynBasePanelUI, wxPanel)
    // begin wxGlade: dynBasePanelUI::event_table
    EVT_BUTTON(wxID_APPLY, dynBasePanelUI::OnApply)
    // end wxGlade
END_EVENT_TABLE();


void dynBasePanelUI::OnApply(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (dynBasePanelUI::OnApply) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


// wxGlade: add dynBasePanelUI event handlers


void dynBasePanelUI::set_properties()
{
    // begin wxGlade: dynBasePanelUI::set_properties
    // end wxGlade
}


void dynBasePanelUI::do_layout()
{
    // begin wxGlade: dynBasePanelUI::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    // end wxGlade
}

