// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Jul 15 16:21:22 2010

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DYNBASEPANELUI_H
#define DYNBASEPANELUI_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class dynBasePanelUI: public wxPanel {
public:
    // begin wxGlade: dynBasePanelUI::ids
    // end wxGlade

    dynBasePanelUI(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    // begin wxGlade: dynBasePanelUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: dynBasePanelUI::attributes
    wxButton* button;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnApply(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // DYNBASEPANELUI_H
