// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Sep 30 16:08:13 2010

#include "coreLandmarkSelectorWidgetUI.h"

// begin wxGlade: ::extracode

// end wxGlade


coreLandmarkSelectorWidgetUI::coreLandmarkSelectorWidgetUI(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxScrolledWindow(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: coreLandmarkSelectorWidgetUI::coreLandmarkSelectorWidgetUI
    m_NewLandmarks = new wxButton(this, wxID_NEW_LANDMARKS, wxT("New Landmarks"));
    m_btnStart = new wxToggleButton(this, wxID_BTN_START, wxT("Start"));
    label_1 = new wxStaticText(this, wxID_ANY, wxT("Landmark name"));
    m_txtCtrlLandmarkName = new wxTextCtrl(this, wxID_TXT_LANDMARK_SELECTOR_WIDGET_LANDMARK_NAME, wxEmptyString);
    const wxString m_radBoxInteractorType_choices[] = {
        wxT("PointSet"),
        wxT("PointSelect")
    };
    m_radBoxInteractorType = new wxRadioBox(this, wxID_RADIO_BOX_INTERACTOR_TYPE, wxT("Interactor type"), wxDefaultPosition, wxDefaultSize, 2, m_radBoxInteractorType_choices, 0, wxRA_SPECIFY_ROWS);

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(coreLandmarkSelectorWidgetUI, wxScrolledWindow)
    // begin wxGlade: coreLandmarkSelectorWidgetUI::event_table
    EVT_BUTTON(wxID_NEW_LANDMARKS, coreLandmarkSelectorWidgetUI::OnNewLandmarks)
    EVT_TOGGLEBUTTON(wxID_BTN_START, coreLandmarkSelectorWidgetUI::OnStart)
    // end wxGlade
END_EVENT_TABLE();


void coreLandmarkSelectorWidgetUI::OnNewLandmarks(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (coreLandmarkSelectorWidgetUI::OnNewLandmarks) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void coreLandmarkSelectorWidgetUI::OnStart(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (coreLandmarkSelectorWidgetUI::OnStart) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


// wxGlade: add coreLandmarkSelectorWidgetUI event handlers


void coreLandmarkSelectorWidgetUI::set_properties()
{
    // begin wxGlade: coreLandmarkSelectorWidgetUI::set_properties
    SetScrollRate(10, 10);
    m_radBoxInteractorType->SetSelection(0);
    // end wxGlade
}


void coreLandmarkSelectorWidgetUI::do_layout()
{
    // begin wxGlade: coreLandmarkSelectorWidgetUI::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxHORIZONTAL);
    sizer_4->Add(m_NewLandmarks, 0, wxALL|wxALIGN_RIGHT, 5);
    sizer_4->Add(m_btnStart, 0, wxALL, 5);
    sizer_1->Add(sizer_4, 0, wxALIGN_RIGHT, 0);
    sizer_2->Add(label_1, 1, wxALL, 5);
    sizer_2->Add(m_txtCtrlLandmarkName, 1, wxALL, 5);
    sizer_1->Add(sizer_2, 0, wxEXPAND, 0);
    sizer_3->Add(m_radBoxInteractorType, 0, wxALL|wxEXPAND, 5);
    sizer_1->Add(sizer_3, 0, wxEXPAND, 0);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    // end wxGlade
}

