// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Sep 30 16:08:13 2010

#include <wx/wx.h>
#include <wx/image.h>

#ifndef CORELANDMARKSELECTORWIDGETUI_H
#define CORELANDMARKSELECTORWIDGETUI_H

// begin wxGlade: ::dependencies
#include <wx/tglbtn.h>
// end wxGlade

// begin wxGlade: ::extracode
#include "wxID.h"
#define wxID_NEW_LANDMARKS wxID( "wxID_NEW_LANDMARKS" )
#define wxID_TXT_LANDMARK_SELECTOR_WIDGET_LANDMARK_NAME wxID(\
	"wxID_TXT_LANDMARK_SELECTOR_WIDGET_LANDMARK_NAME")
#define wxID_RADIO_BOX_INTERACTOR_TYPE wxID(\
	"wxID_RADIO_BOX_INTERACTOR_TYPE")
#define wxID_BTN_START wxID( "wxID_BTN_START" )
// end wxGlade


class coreLandmarkSelectorWidgetUI: public wxScrolledWindow {
public:
    // begin wxGlade: coreLandmarkSelectorWidgetUI::ids
    // end wxGlade

    coreLandmarkSelectorWidgetUI(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    // begin wxGlade: coreLandmarkSelectorWidgetUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: coreLandmarkSelectorWidgetUI::attributes
    wxButton* m_NewLandmarks;
    wxToggleButton* m_btnStart;
    wxStaticText* label_1;
    wxTextCtrl* m_txtCtrlLandmarkName;
    wxRadioBox* m_radBoxInteractorType;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnNewLandmarks(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnStart(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // CORELANDMARKSELECTORWIDGETUI_H
