// -*- C++ -*- generated by wxGlade 0.6.3 on Tue Jun 22 09:29:06 2010

#include "CGNSFileReaderWidgetUI.h"

// begin wxGlade: ::extracode

// end wxGlade


CGNSFileReaderWidgetUI::CGNSFileReaderWidgetUI(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: CGNSFileReaderWidgetUI::CGNSFileReaderWidgetUI
    sizer_2_staticbox = new wxStaticBox(this, -1, wxT("Fields"));
    label_1 = new wxStaticText(this, wxID_ANY, wxT("   Please provide the fields you want to read.   "));
    checkbox_2 = new wxCheckBox(this, wxID_COMP, wxT("Use compression"));

    set_properties();
    do_layout();
    // end wxGlade
}


void CGNSFileReaderWidgetUI::set_properties()
{
    // begin wxGlade: CGNSFileReaderWidgetUI::set_properties
    checkbox_2->SetValue(1);
    // end wxGlade
}


void CGNSFileReaderWidgetUI::do_layout()
{
    // begin wxGlade: CGNSFileReaderWidgetUI::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxStaticBoxSizer* sizer_2 = new wxStaticBoxSizer(sizer_2_staticbox, wxVERTICAL);
    sizer_1->Add(20, 20, 0, 0, 0);
    sizer_1->Add(label_1, 0, wxALL|wxALIGN_CENTER_HORIZONTAL, 0);
    sizer_1->Add(20, 20, 0, 0, 0);
    sizer_1->Add(sizer_2, 1, wxALIGN_CENTER_HORIZONTAL, 0);
    sizer_1->Add(20, 20, 0, 0, 0);
    sizer_1->Add(checkbox_2, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    sizer_1->Add(20, 20, 0, 0, 0);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    // end wxGlade
}

