// -*- C++ -*- generated by wxGlade 0.6.3 on Tue Jun 22 09:29:06 2010

#include <wx/wx.h>
#include <wx/image.h>

#ifndef CGNSFILEREADERWIDGETUI_H
#define CGNSFILEREADERWIDGETUI_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#define wxID_COMP wxID("CGNSFileReaderDialogUIComp")

// end wxGlade


class CGNSFileReaderWidgetUI: public wxPanel {
public:
    // begin wxGlade: CGNSFileReaderWidgetUI::ids
    // end wxGlade

    CGNSFileReaderWidgetUI(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    // begin wxGlade: CGNSFileReaderWidgetUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: CGNSFileReaderWidgetUI::attributes
    wxStaticBox* sizer_2_staticbox;
    wxStaticText* label_1;
    wxCheckBox* checkbox_2;
    // end wxGlade
}; // wxGlade: end class


#endif // CGNSFILEREADERWIDGETUI_H
