// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Aug 02 11:23:00 2010

#include "wxMitkTransformVisualPropWidget.h"

// begin wxGlade: ::extracode

// end wxGlade


wxMitkTransformVisualPropWidget::wxMitkTransformVisualPropWidget(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: wxMitkTransformVisualPropWidget::wxMitkTransformVisualPropWidget
    Offset_staticbox = new wxStaticBox(this, -1, wxT("Offset"));
    Spacing_staticbox = new wxStaticBox(this, -1, wxT("Spacing"));
    label_1 = new wxStaticText(this, wxID_ANY, wxT("X"));
    m_txtSpacingX = new wxTextCtrl(this, wxID_SPACING_X, wxEmptyString);
    label_1_copy = new wxStaticText(this, wxID_ANY, wxT("Y"));
    m_txtSpacingY = new wxTextCtrl(this, wxID_SPACING_Y, wxEmptyString);
    label_1_copy_copy = new wxStaticText(this, wxID_ANY, wxT("Z"));
    m_txtSpacingZ = new wxTextCtrl(this, wxID_SPACING_Z, wxEmptyString);
    label_1_copy_1 = new wxStaticText(this, wxID_ANY, wxT("X"));
    m_txtOffsetX = new wxTextCtrl(this, wxID_OFFSET_X, wxEmptyString);
    label_1_copy_copy_1 = new wxStaticText(this, wxID_ANY, wxT("Y"));
    m_txtOffsetY = new wxTextCtrl(this, wxID_OFFSET_Y, wxEmptyString);
    label_1_copy_copy_copy = new wxStaticText(this, wxID_ANY, wxT("Z"));
    m_txtOffsetZ = new wxTextCtrl(this, wxID_OFFSET_Z, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(wxMitkTransformVisualPropWidget, wxPanel)
    // begin wxGlade: wxMitkTransformVisualPropWidget::event_table
    EVT_TEXT(wxID_SPACING_X, wxMitkTransformVisualPropWidget::OnSpacingX)
    EVT_TEXT(wxID_SPACING_Y, wxMitkTransformVisualPropWidget::OnSpacingY)
    EVT_TEXT(wxID_SPACING_Z, wxMitkTransformVisualPropWidget::OnSpacingZ)
    EVT_TEXT(wxID_OFFSET_X, wxMitkTransformVisualPropWidget::OnOffsetX)
    EVT_TEXT(wxID_OFFSET_Y, wxMitkTransformVisualPropWidget::OnOffsetY)
    EVT_TEXT(wxID_OFFSET_Z, wxMitkTransformVisualPropWidget::OnOffsetZ)
    // end wxGlade
END_EVENT_TABLE();


void wxMitkTransformVisualPropWidget::OnSpacingX(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (wxMitkTransformVisualPropWidget::OnSpacingX) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void wxMitkTransformVisualPropWidget::OnSpacingY(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (wxMitkTransformVisualPropWidget::OnSpacingY) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void wxMitkTransformVisualPropWidget::OnSpacingZ(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (wxMitkTransformVisualPropWidget::OnSpacingZ) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void wxMitkTransformVisualPropWidget::OnOffsetX(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (wxMitkTransformVisualPropWidget::OnOffsetX) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void wxMitkTransformVisualPropWidget::OnOffsetY(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (wxMitkTransformVisualPropWidget::OnOffsetY) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void wxMitkTransformVisualPropWidget::OnOffsetZ(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (wxMitkTransformVisualPropWidget::OnOffsetZ) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


// wxGlade: add wxMitkTransformVisualPropWidget event handlers


void wxMitkTransformVisualPropWidget::set_properties()
{
    // begin wxGlade: wxMitkTransformVisualPropWidget::set_properties
    // end wxGlade
}


void wxMitkTransformVisualPropWidget::do_layout()
{
    // begin wxGlade: wxMitkTransformVisualPropWidget::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxStaticBoxSizer* Offset = new wxStaticBoxSizer(Offset_staticbox, wxVERTICAL);
    wxBoxSizer* sizer_5_copy = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_4_copy = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_3_copy = new wxBoxSizer(wxHORIZONTAL);
    wxStaticBoxSizer* Spacing = new wxStaticBoxSizer(Spacing_staticbox, wxVERTICAL);
    wxBoxSizer* sizer_5 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxHORIZONTAL);
    sizer_3->Add(label_1, 1, wxEXPAND, 0);
    sizer_3->Add(m_txtSpacingX, 1, wxEXPAND, 0);
    Spacing->Add(sizer_3, 1, wxEXPAND, 0);
    sizer_4->Add(label_1_copy, 1, wxEXPAND, 0);
    sizer_4->Add(m_txtSpacingY, 1, wxEXPAND, 0);
    Spacing->Add(sizer_4, 1, wxEXPAND, 0);
    sizer_5->Add(label_1_copy_copy, 1, wxEXPAND, 0);
    sizer_5->Add(m_txtSpacingZ, 1, wxEXPAND, 0);
    Spacing->Add(sizer_5, 1, wxEXPAND, 0);
    sizer_1->Add(Spacing, 0, wxALL|wxEXPAND, 5);
    sizer_3_copy->Add(label_1_copy_1, 1, wxEXPAND, 0);
    sizer_3_copy->Add(m_txtOffsetX, 1, wxEXPAND, 0);
    Offset->Add(sizer_3_copy, 1, wxEXPAND, 0);
    sizer_4_copy->Add(label_1_copy_copy_1, 1, wxEXPAND, 0);
    sizer_4_copy->Add(m_txtOffsetY, 1, wxEXPAND, 0);
    Offset->Add(sizer_4_copy, 1, wxEXPAND, 0);
    sizer_5_copy->Add(label_1_copy_copy_copy, 1, wxEXPAND, 0);
    sizer_5_copy->Add(m_txtOffsetZ, 1, wxEXPAND, 0);
    Offset->Add(sizer_5_copy, 1, wxEXPAND, 0);
    sizer_1->Add(Offset, 0, wxALL|wxEXPAND, 5);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    // end wxGlade
}

