// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Jan 10 18:38:30 2010

#include "wxMitkViewConfiguration.h"

// begin wxGlade: ::extracode

// end wxGlade


wxMitkViewConfiguration::wxMitkViewConfiguration(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: wxMitkViewConfiguration::wxMitkViewConfiguration
    Direction = new wxStaticText(this, wxID_ANY, wxT("Direction"));
    const wxString m_cmbDirection_choices[] = {
        wxT("Sagital"),
        wxT("Transversal"),
        wxT("Coronal")
    };
    m_cmbDirection = new wxComboBox(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, 3, m_cmbDirection_choices, wxCB_DROPDOWN|wxCB_READONLY);
    m_chkFlip = new wxCheckBox(this, wxID_ANY, wxT("Flip"));
    const wxString m_rdbxRotate_choices[] = {
        wxT("0º"),
        wxT("90º"),
        wxT("180º"),
        wxT("270º")
    };
    m_rdbxRotate = new wxRadioBox(this, wxID_ANY, wxT("Rotate"), wxDefaultPosition, wxDefaultSize, 4, m_rdbxRotate_choices, 0, wxRA_SPECIFY_ROWS);

    set_properties();
    do_layout();
    // end wxGlade
}


void wxMitkViewConfiguration::set_properties()
{
    // begin wxGlade: wxMitkViewConfiguration::set_properties
    m_cmbDirection->SetSelection(0);
    m_rdbxRotate->SetSelection(0);
    // end wxGlade
}


void wxMitkViewConfiguration::do_layout()
{
    // begin wxGlade: wxMitkViewConfiguration::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    sizer_2->Add(Direction, 1, wxEXPAND, 0);
    sizer_2->Add(m_cmbDirection, 1, wxEXPAND, 0);
    sizer_1->Add(sizer_2, 0, wxALL|wxEXPAND, 5);
    sizer_1->Add(m_chkFlip, 0, wxALL|wxEXPAND, 5);
    sizer_1->Add(m_rdbxRotate, 0, wxALL|wxEXPAND, 5);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    // end wxGlade
}

