/*
* Copyright (c) 2009,
* Computational Image and Simulation Technologies in Biomedicine (CISTIB),
* Universitat Pompeu Fabra (UPF), Barcelona, Spain. All rights reserved.
* See license.txt file for details.
*/

// -*- C++ -*- generated by wxGlade 0.6.3 on Tue Nov 04 14:11:20 2008

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade


#ifndef COREMOVIETOOLBARUI_H
#define COREMOVIETOOLBARUI_H


// begin wxGlade: ::extracode
// end wxGlade

namespace Core{
namespace Widgets{
/** 
\brief MovieToolbar's User Interface. 
\ingroup gmWidgets
\author 
\sa Core::Widgets::MovieToolbar
*/
class MovieToolbarUI: public wxPanel {
public:
    // begin wxGlade: MovieToolbarUI::ids
    // end wxGlade

    MovieToolbarUI(
		wxWindow* parent, 
		int id, 
		const wxPoint& pos=wxDefaultPosition, 
		const wxSize& size=wxDefaultSize, 
		long style=0);

	bool Enable(bool enable);

private:
    // begin wxGlade: MovieToolbarUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MovieToolbarUI::attributes
    wxStaticBox* sizer_2_staticbox;
    wxStaticBox* frameRateSizer_staticbox;
    wxStaticBox* buttonSizer_staticbox;
    wxBitmapButton* playButton;
    wxBitmapButton* stopButton;
    wxBitmapButton* pauseButton;
    wxSlider* movieSlider;
    wxSlider* frameRateSlider;
    wxTextCtrl* text_ctrl_FrameNr;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnPlayButton(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnStopButton(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnPauseButton(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnMovieSlider(wxScrollEvent &event); // wxGlade: <event_handler>
    virtual void OnFrameRateSlider(wxScrollEvent &event);
}; // wxGlade: end class

} //namespace Widgets
} //namespace Core

#endif // COREMOVIETOOLBARUI_H
