// Copyright 2009 Pompeu Fabra University (Computational Imaging Laboratory), Barcelona, Spain. Web: www.cilab.upf.edu.
// This software is distributed WITHOUT ANY WARRANTY; 
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Jan 14 17:39:16 2010

#include <wx/wx.h>
#include <wx/image.h>

#ifndef ptChangeOrientationWidget_H
#define ptChangeOrientationWidget_H

#include "corePluginMacros.h"
#include "coreProcessingWidget.h"
#include "wxID.h"
#include "coreChangeOrientationProcessor.h"

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#define wxID_BTN_INVERT_SLICE_ORDER wxID( "wxID_BTN_INVERT_SLICE_ORDER" )
#define wxID_BTN_FLIP_UP_DOWN wxID( "wxID_BTN_FLIP_UP_DOWN" )
#define wxID_BTN_FLIP_LEFT_RIGHT wxID( "wxID_BTN_FLIP_LEFT_RIGHT" )

// end wxGlade

class PLUGIN_EXPORT ptChangeOrientationWidget: 
	public wxPanel,
	public Core::Widgets::ProcessingWidget 
{
public:

	coreDefineBaseWindowFactory( ptChangeOrientationWidget )

    // begin wxGlade: ptChangeOrientationWidget::ids
    // end wxGlade

    ptChangeOrientationWidget(
		wxWindow* parent, int id = wxID_ANY, const wxPoint& pos=wxDefaultPosition, 
		const wxSize& size=wxDefaultSize, long style=0);

	//!
	Core::BaseProcessor::Pointer GetProcessor();

private:
    // begin wxGlade: ptChangeOrientationWidget::methods
    void set_properties();
    void do_layout();
    // end wxGlade

	DECLARE_EVENT_TABLE();

	virtual void OnInvertSliceOrder(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnFlipUpDown(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnFlipLeftRight(wxCommandEvent &event); // wxGlade: <event_handler>

protected:
    // begin wxGlade: ptChangeOrientationWidget::attributes
    wxButton* m_btnInvertSliceOrder;
    wxButton* m_btnFlipUp_Down;
    wxButton* m_btnFlipLeft_Right;
	wxStaticBitmap* m_bmpHeadOrientation;
    // end wxGlade

	//!
	Core::ChangeOrientationProcessor::Pointer m_Processor;
}; // wxGlade: end class

#endif // ptChangeOrientationWidget_H
