/*
* Copyright (c) 2009,
* Computational Image and Simulation Technologies in Biomedicine (CISTIB),
* Universitat Pompeu Fabra (UPF), Barcelona, Spain. All rights reserved.
* See license.txt file for details.
*/

// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Feb 19 16:01:27 2009

#include <wx/wx.h>
#include <wx/image.h>
#include "wxID.h"

#ifndef COREBULLEYEPLOTWIDGETUI_H
#define COREBULLEYEPLOTWIDGETUI_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade

#define wxID_BULLS_EYE_CMB_SELECTION wxID("wxID_BULLS_EYE_CMB_SELECTION")

/** 
\brief The Bull Eye Plot Widget UI. 
\ingroup CardioToolsPlugin
\author 
\date 
*/
class coreBullEyePlotWidgetUI: public wxScrolledWindow {
public:
    // begin wxGlade: coreBullEyePlotWidgetUI::ids
    // end wxGlade

    coreBullEyePlotWidgetUI(
		wxWindow* parent, 
		int id, 
		const wxPoint& pos=wxDefaultPosition, 
		const wxSize& size=wxDefaultSize, 
		long style=0);

private:
    // begin wxGlade: coreBullEyePlotWidgetUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: coreBullEyePlotWidgetUI::attributes
    wxStaticBox* m_bullEyePlot_staticbox;
    wxStaticBox* sizer_1_staticbox;
    wxStaticText* m_Title;
    wxStaticText* m_plot;
    wxComboBox* m_ComboBoxSelection;
    wxCheckBox* m_chkSynchronize;
    // end wxGlade
}; // wxGlade: end class


#endif // COREBULLEYEPLOTWIDGETUI_H
