/*
* Copyright (c) 2009,
* Computational Image and Simulation Technologies in Biomedicine (CISTIB),
* Universitat Pompeu Fabra (UPF), Barcelona, Spain. All rights reserved.
* See license.txt file for details.
*/

// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Feb 19 16:01:27 2009

#include "coreBullEyePlotWidgetUI.h"

// begin wxGlade: ::extracode

// end wxGlade


coreBullEyePlotWidgetUI::coreBullEyePlotWidgetUI(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxScrolledWindow(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: coreBullEyePlotWidgetUI::coreBullEyePlotWidgetUI
    m_bullEyePlot_staticbox = new wxStaticBox(this, -1, wxT("Bull's Eye Plot"));
    sizer_1_staticbox = new wxStaticBox(this, -1, wxEmptyString);
    m_Title = new wxStaticText(this, wxID_ANY, wxT("m_Title"), wxDefaultPosition, wxDefaultSize, wxALIGN_CENTRE);
    m_plot = new wxStaticText(this, wxID_ANY, wxT("label"));
    const wxString *m_ComboBoxSelection_choices = NULL;
    m_ComboBoxSelection = new wxComboBox(this, wxID_BULLS_EYE_CMB_SELECTION, wxT(""), wxDefaultPosition, wxDefaultSize, 0, m_ComboBoxSelection_choices, wxCB_DROPDOWN|wxCB_SIMPLE|wxCB_READONLY);
    m_chkSynchronize = new wxCheckBox(this, wxID_ANY, wxT("Synchronize with time"));

    set_properties();
    do_layout();
    // end wxGlade
}


void coreBullEyePlotWidgetUI::set_properties()
{
    // begin wxGlade: coreBullEyePlotWidgetUI::set_properties
    SetScrollRate(10, 10);
    m_Title->SetFont(wxFont(18, wxDEFAULT, wxNORMAL, wxNORMAL, 0, wxT("")));
    // end wxGlade
}


void coreBullEyePlotWidgetUI::do_layout()
{
    // begin wxGlade: coreBullEyePlotWidgetUI::do_layout
    wxStaticBoxSizer* m_bullEyePlot = new wxStaticBoxSizer(m_bullEyePlot_staticbox, wxVERTICAL);
    wxStaticBoxSizer* sizer_1 = new wxStaticBoxSizer(sizer_1_staticbox, wxVERTICAL);
    sizer_1->Add(m_Title, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    sizer_1->Add(m_plot, 1, wxEXPAND|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 0);
    m_bullEyePlot->Add(sizer_1, 1, wxEXPAND, 0);
    m_bullEyePlot->Add(m_ComboBoxSelection, 0, wxEXPAND, 0);
    m_bullEyePlot->Add(m_chkSynchronize, 0, wxALL, 5);
    SetSizer(m_bullEyePlot);
    m_bullEyePlot->Fit(this);
    // end wxGlade
}

