/*
* Copyright (c) 2009,
* Computational Image and Simulation Technologies in Biomedicine (CISTIB),
* Universitat Pompeu Fabra (UPF), Barcelona, Spain. All rights reserved.
* See license.txt file for details.
*/

// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Jul 14 18:17:04 2008

#include <wx/wx.h>
#include <wx/image.h>

#ifndef CORESIMPLEPROGRESSFRAMEUI_H
#define CORESIMPLEPROGRESSFRAMEUI_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


/** 
\brief 
\ingroup gmWidgets
\author 
\date 
*/
class coreSimpleProgressFrameUI: public wxFrame {
public:
    // begin wxGlade: coreSimpleProgressFrameUI::ids
    // end wxGlade

    coreSimpleProgressFrameUI(
		wxWindow* parent, 
		int id, 
		const wxString& title, 
		const wxPoint& pos=wxDefaultPosition, 
		const wxSize& size=wxDefaultSize, 
		long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: coreSimpleProgressFrameUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: coreSimpleProgressFrameUI::attributes
    wxStaticText* label_1;
    // end wxGlade
}; // wxGlade: end class


#endif // CORESIMPLEPROGRESSFRAMEUI_H
