/*
* Copyright (c) 2009,
* Computational Image and Simulation Technologies in Biomedicine (CISTIB),
* Universitat Pompeu Fabra (UPF), Barcelona, Spain. All rights reserved.
* See license.txt file for details.
*/

// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Jul 14 18:17:04 2008

#include "coreSimpleProgressFrameUI.h"

// begin wxGlade: ::extracode

// end wxGlade


coreSimpleProgressFrameUI::coreSimpleProgressFrameUI(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxCAPTION)
{
    // begin wxGlade: coreSimpleProgressFrameUI::coreSimpleProgressFrameUI
    label_1 = new wxStaticText(this, wxID_ANY, wxT("Processing...\nPlease wait."), wxDefaultPosition, wxDefaultSize, wxALIGN_CENTRE);

    set_properties();
    do_layout();
    // end wxGlade
}


void coreSimpleProgressFrameUI::set_properties()
{
    // begin wxGlade: coreSimpleProgressFrameUI::set_properties
    SetTitle(wxT("Processing dialog"));
    SetSize(wxSize(200, 100));
    label_1->SetMinSize(wxSize(82, 32));
    label_1->SetFont(wxFont(10, wxDEFAULT, wxNORMAL, wxBOLD, 0, wxT("")));
    // end wxGlade
}


void coreSimpleProgressFrameUI::do_layout()
{
    // begin wxGlade: coreSimpleProgressFrameUI::do_layout
    wxBoxSizer* GlobalSizer = new wxBoxSizer(wxVERTICAL);
    GlobalSizer->Add(label_1, 0, wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 0);
    SetSizer(GlobalSizer);
    Layout();
    Centre();
    // end wxGlade
}

