// -*- C++ -*- generated by wxGlade 0.6.3 on Tue Dec 21 20:23:40 2010

#include "corePluginConfigurationUI.h"

// begin wxGlade: ::extracode

// end wxGlade


corePluginConfigurationUI::corePluginConfigurationUI(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: corePluginConfigurationUI::corePluginConfigurationUI
    sizer_2_staticbox = new wxStaticBox(this, -1, wxT("Plugin Folders"));
    const wxString *m_listBoxPluginFolders_choices = NULL;
    m_listBoxPluginFolders = new wxListBox(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0, m_listBoxPluginFolders_choices, wxLB_SINGLE);
    m_btnAdd = new wxButton(this, wxID_ADD, wxT("Add"));
    m_btnRemove = new wxButton(this, wxID_REMOVE, wxT("Remove"));
    m_btnReload = new wxButton(this, wxID_RELOAD, wxT("Reload"));

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(corePluginConfigurationUI, wxPanel)
    // begin wxGlade: corePluginConfigurationUI::event_table
    EVT_BUTTON(wxID_ADD, corePluginConfigurationUI::OnAddPluginFolder)
    EVT_BUTTON(wxID_REMOVE, corePluginConfigurationUI::OnRemovePluginFolder)
    EVT_BUTTON(wxID_RELOAD, corePluginConfigurationUI::OnReload)
    // end wxGlade
END_EVENT_TABLE();


void corePluginConfigurationUI::OnAddPluginFolder(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (corePluginConfigurationUI::OnAddPluginFolder) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void corePluginConfigurationUI::OnRemovePluginFolder(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (corePluginConfigurationUI::OnRemovePluginFolder) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void corePluginConfigurationUI::OnReload(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (corePluginConfigurationUI::OnReload) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


// wxGlade: add corePluginConfigurationUI event handlers


void corePluginConfigurationUI::set_properties()
{
    // begin wxGlade: corePluginConfigurationUI::set_properties
    m_btnReload->SetToolTip(wxT("Reload all command line plugins"));
    // end wxGlade
}


void corePluginConfigurationUI::do_layout()
{
    // begin wxGlade: corePluginConfigurationUI::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxStaticBoxSizer* sizer_2 = new wxStaticBoxSizer(sizer_2_staticbox, wxVERTICAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxHORIZONTAL);
    sizer_2->Add(m_listBoxPluginFolders, 1, wxALL|wxEXPAND, 5);
    sizer_3->Add(m_btnAdd, 0, wxALL|wxALIGN_RIGHT, 5);
    sizer_3->Add(m_btnRemove, 0, wxALL|wxALIGN_RIGHT, 5);
    sizer_3->Add(m_btnReload, 0, wxALL|wxALIGN_RIGHT, 5);
    sizer_2->Add(sizer_3, 0, wxALIGN_RIGHT, 0);
    sizer_1->Add(sizer_2, 1, wxALL|wxEXPAND, 5);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    // end wxGlade
}

