// -*- C++ -*- generated by wxGlade 0.6.3 on Tue Dec 21 20:23:40 2010

#include <wx/wx.h>
#include <wx/image.h>

#ifndef COREPLUGINCONFIGURATIONUI_H
#define COREPLUGINCONFIGURATIONUI_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#include "wxID.h"

#define wxID_ADD wxID("wxID_ADD")
#define wxID_REMOVE wxID("wxID_REMOVE")
#define wxID_SCAN wxID( "wxID_SCAN" )
#define wxID_RELOAD wxID( "wxID_RELOAD" )
// end wxGlade


class corePluginConfigurationUI: public wxPanel {
public:
    // begin wxGlade: corePluginConfigurationUI::ids
    // end wxGlade

    corePluginConfigurationUI(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    // begin wxGlade: corePluginConfigurationUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: corePluginConfigurationUI::attributes
    wxStaticBox* sizer_2_staticbox;
    wxListBox* m_listBoxPluginFolders;
    wxButton* m_btnAdd;
    wxButton* m_btnRemove;
    wxButton* m_btnReload;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnAddPluginFolder(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnRemovePluginFolder(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnReload(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // COREPLUGINCONFIGURATIONUI_H
