// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Dec 14 14:28:54 2009

#include "TavernaPluginWorkflowPanelWidgetUI.h"

// begin wxGlade: ::extracode

// end wxGlade


TavernaPluginWorkflowPanelWidgetUI::TavernaPluginWorkflowPanelWidgetUI(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxScrolledWindow(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: TavernaPluginWorkflowPanelWidgetUI::TavernaPluginWorkflowPanelWidgetUI
    m_btnApply = new wxButton(this, wxID_BTN_Apply, wxT("Apply"));

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(TavernaPluginWorkflowPanelWidgetUI, wxScrolledWindow)
    // begin wxGlade: TavernaPluginWorkflowPanelWidgetUI::event_table
    EVT_BUTTON(wxID_BTN_Apply, TavernaPluginWorkflowPanelWidgetUI::OnBtnApply)
    // end wxGlade
END_EVENT_TABLE();


void TavernaPluginWorkflowPanelWidgetUI::OnBtnApply(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (TavernaPluginWorkflowPanelWidgetUI::OnBtnApply) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


// wxGlade: add TavernaPluginWorkflowPanelWidgetUI event handlers


void TavernaPluginWorkflowPanelWidgetUI::set_properties()
{
    // begin wxGlade: TavernaPluginWorkflowPanelWidgetUI::set_properties
    SetScrollRate(10, 10);
    // end wxGlade
}


void TavernaPluginWorkflowPanelWidgetUI::do_layout()
{
    // begin wxGlade: TavernaPluginWorkflowPanelWidgetUI::do_layout
    wxBoxSizer* GlobalSizer = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    sizer_1->Add(m_btnApply, 0, wxALL|wxEXPAND, 5);
    GlobalSizer->Add(sizer_1, 0, wxEXPAND, 5);
    SetSizer(GlobalSizer);
    GlobalSizer->Fit(this);
    // end wxGlade
}

