// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Aug 07 10:09:20 2009

#include <wx/wx.h>
#include <wx/image.h>

#ifndef CORETHUMBNAILWIDGETUI_H
#define CORETHUMBNAILWIDGETUI_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#include "wxID.h"
#define wxID_BTN_SHOW wxID("wxID_BTN_SHOW")

// end wxGlade


class coreThumbnailWidgetUI: public wxScrolledWindow {
public:
    // begin wxGlade: coreThumbnailWidgetUI::ids
    // end wxGlade

    coreThumbnailWidgetUI(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    // begin wxGlade: coreThumbnailWidgetUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: coreThumbnailWidgetUI::attributes
    // end wxGlade
}; // wxGlade: end class


#endif // CORETHUMBNAILWIDGETUI_H
