// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Aug 07 10:09:20 2009

#include "coreThumbnailWidgetUI.h"

// begin wxGlade: ::extracode

// end wxGlade


coreThumbnailWidgetUI::coreThumbnailWidgetUI(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxScrolledWindow(parent, id, pos, size, style)
{
    // begin wxGlade: coreThumbnailWidgetUI::coreThumbnailWidgetUI

    set_properties();
    do_layout();
    // end wxGlade
}


void coreThumbnailWidgetUI::set_properties()
{
    // begin wxGlade: coreThumbnailWidgetUI::set_properties
    SetScrollRate(10, 10);
    // end wxGlade
}


void coreThumbnailWidgetUI::do_layout()
{
    // begin wxGlade: coreThumbnailWidgetUI::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    // end wxGlade
}

