/*
* Copyright (c) 2009,
* Computational Image and Simulation Technologies in Biomedicine (CISTIB),
* Universitat Pompeu Fabra (UPF), Barcelona, Spain. All rights reserved.
* See license.txt file for details.
*/
// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Sep 18 10:45:14 2008

#include "corePointsTableWidgetUI.h"

// begin wxGlade: ::extracode

// end wxGlade


corePointsTableWidgetUI::corePointsTableWidgetUI(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: corePointsTableWidgetUI::corePointsTableWidgetUI
    m_sizer_staticbox = new wxStaticBox(this, -1, wxT("Table of points"));
    m_list_ctrl = new wxListCtrl(this, wxID_LIST_CONTROL_POINTS, wxDefaultPosition, wxDefaultSize, wxLC_REPORT|wxLC_AUTOARRANGE|wxSUNKEN_BORDER);

    set_properties();
    do_layout();
    // end wxGlade
}


void corePointsTableWidgetUI::set_properties()
{
    // begin wxGlade: corePointsTableWidgetUI::set_properties
    // end wxGlade
}


void corePointsTableWidgetUI::do_layout()
{
    // begin wxGlade: corePointsTableWidgetUI::do_layout
    wxStaticBoxSizer* m_sizer = new wxStaticBoxSizer(m_sizer_staticbox, wxVERTICAL);
    m_sizer->Add(m_list_ctrl, 1, wxALL|wxEXPAND, 0);
    SetSizer(m_sizer);
    m_sizer->Fit(this);
    // end wxGlade
}

