/*
* Copyright (c) 2009,
* Computational Image and Simulation Technologies in Biomedicine (CISTIB),
* Universitat Pompeu Fabra (UPF), Barcelona, Spain. All rights reserved.
* See license.txt file for details.
*/

// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Sep 18 10:45:14 2008

#include <wx/wx.h>
#include <wx/image.h>
#include "wxID.h"

#ifndef COREPOINTSTABLEWIDGETUI_H
#define COREPOINTSTABLEWIDGETUI_H

// begin wxGlade: ::dependencies
#include <wx/listctrl.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade

#define wxID_LIST_CONTROL_POINTS wxID( "corePointsTableWidgetUIListControlPoints" )

/** 
\brief 
\ingroup gmWidgets
\author 
\date 
*/
class corePointsTableWidgetUI: public wxPanel {
public:
    // begin wxGlade: corePointsTableWidgetUI::ids
    // end wxGlade

    corePointsTableWidgetUI(
		wxWindow* parent,
		int id, 
		const wxPoint& pos=wxDefaultPosition, 
		const wxSize& size=wxDefaultSize, 
		long style=0);

private:
    // begin wxGlade: corePointsTableWidgetUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: corePointsTableWidgetUI::attributes
    wxStaticBox* m_sizer_staticbox;
    wxListCtrl* m_list_ctrl;
    // end wxGlade

protected:
}; // wxGlade: end class


#endif // COREPOINTSTABLEWIDGETUI_H
