// -*- C++ -*- generated by wxGlade 0.6.3 on Tue Jun 29 11:40:30 2010

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DICOMCONNECTTOPACSDIALOGWIDGETUI_H
#define DICOMCONNECTTOPACSDIALOGWIDGETUI_H

// begin wxGlade: ::dependencies
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/datectrl.h>
// end wxGlade

// begin wxGlade: ::extracode
#include "wxID.h"
#include "DicomTree.h"

#define wxID_DICOM_OPEN_DIRECTORY_FOR_SAVING_PACS_DATA wxID("DicomOpenDirectoryForSavingPacsData")
#define wxID_DICOM_QUERY wxID("wxID_DICOM_QUERY")
#define wxID_DICOM_RETRIEVE wxID("wxID_DICOM_RETRIEVE")
#define wxID_DICOM_SEND wxID("wxID_DICOM_SEND")
#define wxID_DICOM_SAVECONFIG wxID("wxID_DICOM_SAVECONFIG")
#define wxID_DICOM_PATIENT_NAME wxID("wxID_DICOM_PATIENT_NAME")
#define wxID_DICOM_PATIENT_BIRTH_DATE wxID("wxID_DICOM_PATIENT_BIRTH_DATE")
#define wxID_DICOM_PATIENT_BIRTH_FROM wxID("wxID_DICOM_PATIENT_BIRTH_FROM")
#define wxID_DICOM_PATIENT_BIRTH_TO wxID("wxID_DICOM_PATIENT_BIRTH_TO")
#define wxID_DICOM_PATIENT_ID wxID("wxID_DICOM_PATIENT_ID")
#define wxID_DICOM_PATIENT_DATE_OF_BIRTH wxID("wxID_DICOM_PATIENT_DATE_OF_BIRTH")
#define wxID_DICOM_PATIENT_DATE_OF_BIRTH_FROM wxID("wxID_DICOM_PATIENT_DATE_OF_BIRTH_FROM")
#define wxID_DICOM_PATIENT_DATE_OF_BIRTH_TO wxID("wxID_DICOM_PATIENT_DATE_OF_BIRTH_TO")
#define wxID_DICOM_STUDY_ID wxID("wxID_DICOM_STUDY_ID")
#define wxID_DICOM_MODALITY wxID("wxID_DICOM_MODALITY")

// end wxGlade


class DicomConnectToPacsDialogWidgetUI: public wxScrolledWindow {
public:
    // begin wxGlade: DicomConnectToPacsDialogWidgetUI::ids
    // end wxGlade

    DicomConnectToPacsDialogWidgetUI(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    // begin wxGlade: DicomConnectToPacsDialogWidgetUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DicomConnectToPacsDialogWidgetUI::attributes
    wxStaticBox* sizer_2_staticbox;
    wxStaticBox* sizer_6_copy_staticbox;
    wxStaticBox* sizer_8_staticbox;
    wxStaticBox* sizer_5_staticbox;
    wxStaticText* label_1;
    wxTextCtrl* m_edPatientName;
    wxStaticText* label_PatientID;
    wxTextCtrl* m_edPatientID;
    wxCheckBox* m_chkDateOfBirth;
    wxCheckBox* m_chkDateOfBirthFrom;
    wxCheckBox* m_chkDateOfBirthTo;
    wxDatePickerCtrl* m_dateBirth;
    wxDatePickerCtrl* m_dateBirth_From;
    wxDatePickerCtrl* m_dateBirth_To;
    wxStaticText* label_StudyId;
    wxTextCtrl* m_edStudyId;
    wxStaticText* label_Modality;
    wxTextCtrl* m_edModality;
    wxStaticText* label_2;
    wxTextCtrl* m_edSaveToDirectory;
    wxButton* m_btnOpenDirectoryForSavingPacsData;
    wxButton* m_btnQuery;
    wxButton* m_btnRetrieve;
    DicomPlugin::DICOMTree* m_DICOMTree;
    wxPanel* notebook_pane_QueryRetrieve;
    wxStaticText* label_SendToPacs;
    wxButton* m_btnSendToPacs;
    wxPanel* notebook_pane_SendToPacs;
    wxStaticText* label_Calling_AE;
    wxTextCtrl* m_edPACSCallingAETitle;
    wxStaticText* label_CallerAE;
    wxTextCtrl* m_edPACSCalledAETitle;
    wxStaticText* label_CallingAEIPAddress;
    wxTextCtrl* m_edPACSCallingAEIP;
    wxStaticText* label_CalledAEIPAddress;
    wxTextCtrl* m_edPACSCalledAEIP;
    wxStaticText* label_CallingPortNumber_copy;
    wxTextCtrl* m_edPACSCallingAEPortRetrieve;
    wxStaticText* label_CallingPortNumber;
    wxTextCtrl* m_edPACSCallingAEPortSend;
    wxStaticText* label_CalledPortNumber;
    wxTextCtrl* m_edPACSCalledAEPort;
    wxButton* m_btnSaveConfig;
    wxPanel* notebook_pane_ConnectionParams;
    wxNotebook* notebook;
    // end wxGlade
}; // wxGlade: end class


#endif // DICOMCONNECTTOPACSDIALOGWIDGETUI_H
