// -*- C++ -*- generated by wxGlade 0.6.3 on Wed Dec 01 09:12:44 2010

#include "coreUserRegistrationDialogUI.h"

// begin wxGlade: ::extracode

// end wxGlade


coreUserRegistrationDialogUI::coreUserRegistrationDialogUI(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: coreUserRegistrationDialogUI::coreUserRegistrationDialogUI
    m_bmpGIMIAS = new wxStaticBitmap(this, wxID_ANY, wxNullBitmap);
    label_1 = new wxStaticText(this, wxID_ANY, wxT("Welcome to GIMIAS User Registration Form"));
    static_line_1 = new wxStaticLine(this, wxID_ANY);
    label_2 = new wxStaticText(this, wxID_ANY, wxT("Benefits:\n- Allow us to support you better. Understand your needs to align future GIMIAS features\n- Update you with new GIMIAS releases, workshops and other news (Optionally)"));
    static_line_2 = new wxStaticLine(this, wxID_ANY);
    label_3 = new wxStaticText(this, wxID_ANY, wxT("First name *"));
    m_FirstName = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    label_3_copy = new wxStaticText(this, wxID_ANY, wxT("Last name *"));
    m_LastName = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    label_3_copy_copy = new wxStaticText(this, wxID_ANY, wxT("Email address *"));
    m_EmailAddress = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    label_3_copy_copy_copy = new wxStaticText(this, wxID_ANY, wxT("Subscribe to GIMIAS newsletter"));
    m_chkNewsletter = new wxCheckBox(this, wxID_ANY, wxEmptyString);
    label_3_copy_copy_copy_1 = new wxStaticText(this, wxID_ANY, wxT("Institution/Company *"));
    m_Company = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    label_3_copy_copy_copy_1_copy = new wxStaticText(this, wxID_ANY, wxT("Research field"));
    m_ResearchField = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    label_3_copy_copy_copy_1_copy_copy = new wxStaticText(this, wxID_ANY, wxT("Please tell us why you are using GIMIAS"));
    m_UsingGIMIAS = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    static_line_3 = new wxStaticLine(this, wxID_ANY);
    m_btnRegister = new wxButton(this, wxID_BTN_REGISTER, wxT("Register"));
    m_btnRemindMeLater = new wxButton(this, wxID_BTN_REMIND_ME_LATER, wxT("Remind me later"));
    m_btnDoNotAsk = new wxButton(this, wxID_BTN_DO_NOT_ASK, wxT("Do not ask me again"));

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(coreUserRegistrationDialogUI, wxDialog)
    // begin wxGlade: coreUserRegistrationDialogUI::event_table
    EVT_BUTTON(wxID_BTN_REGISTER, coreUserRegistrationDialogUI::OnRegister)
    EVT_BUTTON(wxID_BTN_REMIND_ME_LATER, coreUserRegistrationDialogUI::OnRemindMe)
    EVT_BUTTON(wxID_BTN_DO_NOT_ASK, coreUserRegistrationDialogUI::OnDoNotAsk)
    // end wxGlade
END_EVENT_TABLE();


void coreUserRegistrationDialogUI::OnRegister(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (coreUserRegistrationDialogUI::OnRegister) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void coreUserRegistrationDialogUI::OnRemindMe(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (coreUserRegistrationDialogUI::OnRemindMe) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void coreUserRegistrationDialogUI::OnDoNotAsk(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (coreUserRegistrationDialogUI::OnDoNotAsk) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


// wxGlade: add coreUserRegistrationDialogUI event handlers


void coreUserRegistrationDialogUI::set_properties()
{
    // begin wxGlade: coreUserRegistrationDialogUI::set_properties
    SetTitle(wxT("GIMIAS User Registration"));
    SetSize(wxSize(470, 485));
    m_bmpGIMIAS->SetMinSize(wxSize(64, 64));
    label_1->SetFont(wxFont(12, wxDEFAULT, wxNORMAL, wxBOLD, 0, wxT("")));
    m_chkNewsletter->SetValue(1);
    m_UsingGIMIAS->SetMinSize(wxSize(244, 84));
    // end wxGlade
}


void coreUserRegistrationDialogUI::do_layout()
{
    // begin wxGlade: coreUserRegistrationDialogUI::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_5 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_4_copy_copy_copy_1_copy_copy = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_4_copy_copy_copy_1_copy = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_4_copy_copy_copy_1 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_4_copy_copy_copy = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_4_copy_copy = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_4_copy = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    sizer_2->Add(m_bmpGIMIAS, 0, wxALL, 5);
    sizer_2->Add(label_1, 0, wxALIGN_CENTER_VERTICAL, 0);
    sizer_1->Add(sizer_2, 0, wxALL|wxEXPAND, 5);
    sizer_1->Add(static_line_1, 0, wxEXPAND, 0);
    sizer_3->Add(label_2, 0, 0, 0);
    sizer_1->Add(sizer_3, 0, wxALL|wxEXPAND, 5);
    sizer_1->Add(static_line_2, 0, wxEXPAND, 0);
    sizer_4->Add(label_3, 1, 0, 0);
    sizer_4->Add(m_FirstName, 1, 0, 0);
    sizer_1->Add(sizer_4, 0, wxALL|wxEXPAND, 5);
    sizer_4_copy->Add(label_3_copy, 1, 0, 0);
    sizer_4_copy->Add(m_LastName, 1, 0, 0);
    sizer_1->Add(sizer_4_copy, 0, wxALL|wxEXPAND, 5);
    sizer_4_copy_copy->Add(label_3_copy_copy, 1, 0, 0);
    sizer_4_copy_copy->Add(m_EmailAddress, 1, 0, 0);
    sizer_1->Add(sizer_4_copy_copy, 0, wxALL|wxEXPAND, 5);
    sizer_4_copy_copy_copy->Add(label_3_copy_copy_copy, 1, 0, 0);
    sizer_4_copy_copy_copy->Add(m_chkNewsletter, 1, 0, 0);
    sizer_1->Add(sizer_4_copy_copy_copy, 0, wxALL|wxEXPAND, 5);
    sizer_4_copy_copy_copy_1->Add(label_3_copy_copy_copy_1, 1, 0, 0);
    sizer_4_copy_copy_copy_1->Add(m_Company, 1, 0, 0);
    sizer_1->Add(sizer_4_copy_copy_copy_1, 0, wxALL|wxEXPAND, 5);
    sizer_4_copy_copy_copy_1_copy->Add(label_3_copy_copy_copy_1_copy, 1, 0, 0);
    sizer_4_copy_copy_copy_1_copy->Add(m_ResearchField, 1, 0, 0);
    sizer_1->Add(sizer_4_copy_copy_copy_1_copy, 0, wxALL|wxEXPAND, 5);
    sizer_4_copy_copy_copy_1_copy_copy->Add(label_3_copy_copy_copy_1_copy_copy, 1, 0, 0);
    sizer_4_copy_copy_copy_1_copy_copy->Add(m_UsingGIMIAS, 1, wxEXPAND, 0);
    sizer_1->Add(sizer_4_copy_copy_copy_1_copy_copy, 0, wxALL|wxEXPAND, 5);
    sizer_1->Add(static_line_3, 0, wxEXPAND, 0);
    sizer_5->Add(m_btnRegister, 0, wxALL, 5);
    sizer_5->Add(m_btnRemindMeLater, 0, wxALL, 5);
    sizer_5->Add(m_btnDoNotAsk, 0, wxALL, 5);
    sizer_1->Add(sizer_5, 0, wxALL|wxALIGN_CENTER_HORIZONTAL, 5);
    SetSizer(sizer_1);
    Layout();
    // end wxGlade
}

