// -*- C++ -*- generated by wxGlade 0.6.3 on Wed Dec 01 09:12:44 2010

#include <wx/wx.h>
#include <wx/image.h>

#ifndef COREUSERREGISTRATIONDIALOGUI_H
#define COREUSERREGISTRATIONDIALOGUI_H

// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade

// begin wxGlade: ::extracode
#include "wxID.h"

#define wxID_BTN_REGISTER wxID( "wxID_BTN_REGISTER" )
#define wxID_BTN_REMIND_ME_LATER wxID( "wxID_BTN_REMIND_ME_LATER")
#define wxID_BTN_DO_NOT_ASK wxID( "wxID_BTN_DO_NOT_ASK")

// end wxGlade


class coreUserRegistrationDialogUI: public wxDialog {
public:
    // begin wxGlade: coreUserRegistrationDialogUI::ids
    // end wxGlade

    coreUserRegistrationDialogUI(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: coreUserRegistrationDialogUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: coreUserRegistrationDialogUI::attributes
    wxStaticBitmap* m_bmpGIMIAS;
    wxStaticText* label_1;
    wxStaticLine* static_line_1;
    wxStaticText* label_2;
    wxStaticLine* static_line_2;
    wxStaticText* label_3;
    wxTextCtrl* m_FirstName;
    wxStaticText* label_3_copy;
    wxTextCtrl* m_LastName;
    wxStaticText* label_3_copy_copy;
    wxTextCtrl* m_EmailAddress;
    wxStaticText* label_3_copy_copy_copy;
    wxCheckBox* m_chkNewsletter;
    wxStaticText* label_3_copy_copy_copy_1;
    wxTextCtrl* m_Company;
    wxStaticText* label_3_copy_copy_copy_1_copy;
    wxTextCtrl* m_ResearchField;
    wxStaticText* label_3_copy_copy_copy_1_copy_copy;
    wxTextCtrl* m_UsingGIMIAS;
    wxStaticLine* static_line_3;
    wxButton* m_btnRegister;
    wxButton* m_btnRemindMeLater;
    wxButton* m_btnDoNotAsk;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnRegister(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnRemindMe(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnDoNotAsk(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // COREUSERREGISTRATIONDIALOGUI_H
