// -*- C++ -*- generated by wxGlade 0.6.3 on Mon May 03 18:02:30 2010

#include <wx/wx.h>
#include <wx/image.h>

#ifndef PTSIGNALTIMEPROPAGATIONPANELWIDGETUI_H
#define PTSIGNALTIMEPROPAGATIONPANELWIDGETUI_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#define wxID_btnSignalTimePropagation wxID( "wxID_btnSignalTimePropagation" )
#define wxID_txtMarkersPerScan wxID( "wxID_txtMarkersPerScan" )
// end wxGlade


class ptSignalTimePropagationPanelWidgetUI: public wxPanel {
public:
    // begin wxGlade: ptSignalTimePropagationPanelWidgetUI::ids
    // end wxGlade

    ptSignalTimePropagationPanelWidgetUI(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    // begin wxGlade: ptSignalTimePropagationPanelWidgetUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: ptSignalTimePropagationPanelWidgetUI::attributes
    wxStaticText* label_1;
    wxTextCtrl* m_txtMarkersPerScan;
    wxButton* m_btnSignalTimePropagation;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnMarkersPerScan(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnButtonSignalTimePropagation(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // PTSIGNALTIMEPROPAGATIONPANELWIDGETUI_H
