// -*- C++ -*- generated by wxGlade 0.6.3 on Wed Oct 13 11:04:52 2010

#include "MultiLevelROIPanelWidgetUI.h"

// begin wxGlade: ::extracode

// end wxGlade


MultiLevelROIPanelWidgetUI::MultiLevelROIPanelWidgetUI(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxScrolledWindow(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: MultiLevelROIPanelWidgetUI::MultiLevelROIPanelWidgetUI
    sizer_1_staticbox = new wxStaticBox(this, -1, wxT("Measures"));
    sizer_9_staticbox = new wxStaticBox(this, -1, wxT("Propagate Over Time"));
    m_btnPropagate = new wxButton(this, wxID_BTN_PROPAGATE, wxT("Apply"));
    label_3 = new wxStaticText(this, wxID_ANY, wxT("Left   "));
    m_spinCtrlLeft = new wxSpinCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, -1000, 0);
    label_8 = new wxStaticText(this, wxID_ANY, wxT("Right   "));
    m_spinCtrlRight = new wxSpinCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 1000);
    label_4 = new wxStaticText(this, wxID_ANY, wxT("Mean"));
    m_measureMean = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    label_7 = new wxStaticText(this, wxID_ANY, wxT("Standard deviation"));
    m_measureSTD = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    label_5 = new wxStaticText(this, wxID_ANY, wxT("Minimum"));
    m_measureMin = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    label_6 = new wxStaticText(this, wxID_ANY, wxT("Maximum"));
    m_measureMax = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    button_1 = new wxButton(this, wxID_BTN_UPDATEMEASURES, wxT("Update"));
    label_1 = new wxStaticText(this, wxID_ANY, wxT("Level"));
    const wxString *m_comboBoxLevels_choices = NULL;
    m_comboBoxLevels = new wxComboBox(this, wxID_CMB_LEVELS , wxT(""), wxDefaultPosition, wxDefaultSize, 0, m_comboBoxLevels_choices, wxCB_DROPDOWN);
    button_2 = new wxButton(this, wxID_BTN_CREATESIGNAL, wxT("Create signal"));
    label_2 = new wxStaticText(this, wxID_ANY, wxT("Domain"));
    m_rb3d = new wxRadioButton(this, wxID_ANY, wxT("3D"));
    m_rbX = new wxRadioButton(this, wxID_ANY, wxT("X"));
    m_rbY = new wxRadioButton(this, wxID_ANY, wxT("Y"));
    m_rbZ = new wxRadioButton(this, wxID_ANY, wxT("Z"));

    set_properties();
    do_layout();
    // end wxGlade
}


void MultiLevelROIPanelWidgetUI::set_properties()
{
    // begin wxGlade: MultiLevelROIPanelWidgetUI::set_properties
    SetScrollRate(10, 10);
    m_rb3d->SetValue(1);
    // end wxGlade
}


void MultiLevelROIPanelWidgetUI::do_layout()
{
    // begin wxGlade: MultiLevelROIPanelWidgetUI::do_layout
    wxBoxSizer* GlobalSizer = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    wxGridSizer* grid_sizer_1 = new wxGridSizer(2, 2, 0, 0);
    wxBoxSizer* sizer_6 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_7 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxVERTICAL);
    wxStaticBoxSizer* sizer_1 = new wxStaticBoxSizer(sizer_1_staticbox, wxHORIZONTAL);
    wxGridSizer* grid_sizer_2 = new wxGridSizer(4, 2, 0, 0);
    wxStaticBoxSizer* sizer_9 = new wxStaticBoxSizer(sizer_9_staticbox, wxHORIZONTAL);
    wxGridSizer* grid_sizer_5 = new wxGridSizer(2, 2, 0, 0);
    wxBoxSizer* sizer_5 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxHORIZONTAL);
    grid_sizer_5->Add(m_btnPropagate, 0, wxEXPAND, 0);
    sizer_4->Add(label_3, 0, 0, 0);
    sizer_4->Add(m_spinCtrlLeft, 0, 0, 0);
    grid_sizer_5->Add(sizer_4, 0, wxALIGN_RIGHT, 0);
    grid_sizer_5->Add(20, 20, 0, 0, 0);
    sizer_5->Add(label_8, 0, wxALIGN_RIGHT, 0);
    sizer_5->Add(m_spinCtrlRight, 0, 0, 0);
    grid_sizer_5->Add(sizer_5, 0, wxALIGN_RIGHT, 0);
    sizer_9->Add(grid_sizer_5, 1, 0, 0);
    GlobalSizer->Add(sizer_9, 0, wxEXPAND, 0);
    grid_sizer_2->Add(label_4, 0, 0, 0);
    grid_sizer_2->Add(m_measureMean, 1, wxEXPAND, 0);
    grid_sizer_2->Add(label_7, 0, 0, 0);
    grid_sizer_2->Add(m_measureSTD, 1, wxEXPAND, 0);
    grid_sizer_2->Add(label_5, 0, 0, 0);
    grid_sizer_2->Add(m_measureMin, 1, wxEXPAND, 0);
    grid_sizer_2->Add(label_6, 0, 0, 0);
    grid_sizer_2->Add(m_measureMax, 1, wxEXPAND, 0);
    sizer_1->Add(grid_sizer_2, 1, wxEXPAND, 0);
    GlobalSizer->Add(sizer_1, 0, wxEXPAND, 0);
    grid_sizer_1->Add(button_1, 0, wxEXPAND, 0);
    sizer_3->Add(label_1, 0, wxALL, 5);
    sizer_3->Add(m_comboBoxLevels, 0, wxALL, 5);
    grid_sizer_1->Add(sizer_3, 5, wxALL|wxEXPAND, 0);
    grid_sizer_1->Add(button_2, 0, wxEXPAND, 0);
    sizer_6->Add(label_2, 0, wxALL, 5);
    sizer_7->Add(m_rb3d, 0, 0, 0);
    sizer_7->Add(m_rbX, 0, 0, 0);
    sizer_7->Add(m_rbY, 0, 0, 0);
    sizer_7->Add(m_rbZ, 0, 0, 0);
    sizer_6->Add(sizer_7, 1, wxALL|wxEXPAND, 5);
    grid_sizer_1->Add(sizer_6, 0, wxEXPAND, 0);
    sizer_2->Add(grid_sizer_1, 1, wxEXPAND, 0);
    GlobalSizer->Add(sizer_2, 0, wxEXPAND, 0);
    SetSizer(GlobalSizer);
    GlobalSizer->Fit(this);
    // end wxGlade
}

