// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Aug 27 15:06:19 2010

#include "coreWorkingAreaManagerWidgetUI.h"

// begin wxGlade: ::extracode

// end wxGlade


coreWorkingAreaManagerWidgetUI::coreWorkingAreaManagerWidgetUI(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxScrolledWindow(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: coreWorkingAreaManagerWidgetUI::coreWorkingAreaManagerWidgetUI
    sizer_3_staticbox = new wxStaticBox(this, -1, wxEmptyString);
    ManageWorkingAreas_staticbox = new wxStaticBox(this, -1, wxEmptyString);
    const wxString *m_List_choices = NULL;
    m_List = new wxListBox(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0, m_List_choices, 0);
    m_btnNew = new wxButton(this, wxID_BTN_NEW, wxT("New"));
    m_btnRename = new wxButton(this, wxID_BTN_RENAME, wxT("Rename"));
    m_btnSave = new wxButton(this, wxID_BTN_SAVE, wxT("Save"));
    m_btnDelete = new wxButton(this, wxID_BTN_DELETE, wxT("Delete"));

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(coreWorkingAreaManagerWidgetUI, wxScrolledWindow)
    // begin wxGlade: coreWorkingAreaManagerWidgetUI::event_table
    EVT_LISTBOX(wxID_ANY, coreWorkingAreaManagerWidgetUI::OnSelectedWorkingArea)
    EVT_BUTTON(wxID_BTN_NEW, coreWorkingAreaManagerWidgetUI::OnNew)
    EVT_BUTTON(wxID_BTN_RENAME, coreWorkingAreaManagerWidgetUI::OnRename)
    EVT_BUTTON(wxID_BTN_SAVE, coreWorkingAreaManagerWidgetUI::OnSave)
    EVT_BUTTON(wxID_BTN_DELETE, coreWorkingAreaManagerWidgetUI::OnDelete)
    // end wxGlade
END_EVENT_TABLE();


void coreWorkingAreaManagerWidgetUI::OnSelectedWorkingArea(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (coreWorkingAreaManagerWidgetUI::OnSelectedWorkingArea) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void coreWorkingAreaManagerWidgetUI::OnNew(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (coreWorkingAreaManagerWidgetUI::OnNew) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void coreWorkingAreaManagerWidgetUI::OnRename(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (coreWorkingAreaManagerWidgetUI::OnRename) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void coreWorkingAreaManagerWidgetUI::OnSave(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (coreWorkingAreaManagerWidgetUI::OnSave) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void coreWorkingAreaManagerWidgetUI::OnDelete(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (coreWorkingAreaManagerWidgetUI::OnDelete) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


// wxGlade: add coreWorkingAreaManagerWidgetUI event handlers


void coreWorkingAreaManagerWidgetUI::set_properties()
{
    // begin wxGlade: coreWorkingAreaManagerWidgetUI::set_properties
    SetSize(wxSize(273, 279));
    SetScrollRate(10, 10);
    // end wxGlade
}


void coreWorkingAreaManagerWidgetUI::do_layout()
{
    // begin wxGlade: coreWorkingAreaManagerWidgetUI::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxStaticBoxSizer* sizer_3 = new wxStaticBoxSizer(sizer_3_staticbox, wxHORIZONTAL);
    wxGridSizer* grid_sizer_1 = new wxGridSizer(2, 2, 2, 2);
    wxStaticBoxSizer* ManageWorkingAreas = new wxStaticBoxSizer(ManageWorkingAreas_staticbox, wxVERTICAL);
    ManageWorkingAreas->Add(m_List, 0, wxEXPAND, 0);
    sizer_1->Add(ManageWorkingAreas, 0, wxALL|wxEXPAND, 5);
    grid_sizer_1->Add(m_btnNew, 0, wxEXPAND, 0);
    grid_sizer_1->Add(m_btnRename, 0, wxEXPAND, 0);
    grid_sizer_1->Add(m_btnSave, 0, wxEXPAND, 0);
    grid_sizer_1->Add(m_btnDelete, 0, wxEXPAND, 0);
    sizer_3->Add(grid_sizer_1, 1, wxEXPAND, 0);
    sizer_1->Add(sizer_3, 0, wxALL|wxEXPAND, 5);
    SetSizer(sizer_1);
    // end wxGlade
}

