// -*- C++ -*- generated by wxGlade 0.6.3 on Wed Jun 30 10:34:37 2010

#include <wx/wx.h>
#include <wx/image.h>

#ifndef COREWORKFLOWEDITORWIDGETUI_H
#define COREWORKFLOWEDITORWIDGETUI_H

// begin wxGlade: ::dependencies
#include <wx/treectrl.h>
// end wxGlade

// begin wxGlade: ::extracode
#include "wxID.h"
#include "blwxTreeCtrl.h"
#include "coreTreeWorkflow.h"
#include "coreTreeRegisteredWindows.h"

#define wxID_TREE_REGISTERED_WINDOWS wxID( "wxID_TREE_REGISTERED_WINDOWS" )
#define wxID_TREE_WORKFLOW wxID( "wxID_TREE_WORKFLOW" )


// end wxGlade


class coreWorkflowEditorWidgetUI: public wxDialog {
public:
    // begin wxGlade: coreWorkflowEditorWidgetUI::ids
    // end wxGlade

    coreWorkflowEditorWidgetUI(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: coreWorkflowEditorWidgetUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: coreWorkflowEditorWidgetUI::attributes
    wxStaticBox* sizer_4_staticbox;
    wxStaticBox* sizer_3_staticbox;
    Core::Widgets::TreeRegisteredWindows* m_TreeRegisteredWindows;
    Core::Widgets::TreeWorkflow* m_TreeWorkflow;
    wxStaticText* label_1;
    wxButton* m_btnOk;
    wxButton* m_btnCancel;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnOk(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnCancel(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // COREWORKFLOWEDITORWIDGETUI_H
