// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Oct 01 14:37:23 2010

#include "coreWorkflowManagerWidgetUI.h"

// begin wxGlade: ::extracode

// end wxGlade


coreWorkflowManagerWidgetUI::coreWorkflowManagerWidgetUI(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxTHICK_FRAME)
{
    // begin wxGlade: coreWorkflowManagerWidgetUI::coreWorkflowManagerWidgetUI
    m_bmpBitmap = new wxStaticBitmap(this, wxID_ANY, wxNullBitmap);
    m_treeWorkflows = new wxTreeCtrlWorkflows(this, wxID_TREE_WORKFLOWS, wxDefaultPosition, wxDefaultSize, wxTR_HAS_BUTTONS|wxTR_LINES_AT_ROOT|wxTR_DEFAULT_STYLE|wxSUNKEN_BORDER);
    m_btnNew = new wxButton(this, wxID_BTN_NEW, wxT("New"));
    m_btnEdit = new wxButton(this, wxID_BTN_EDIT, wxT("Edit"));
    m_btnRename = new wxButton(this, wxID_BTN_RENAME, wxT("Rename"));
    m_btnActivate = new wxButton(this, wxID_BTN_ACTIVATE, wxT("Activate"));
    m_btnDelete = new wxButton(this, wxID_BTN_DELETE, wxT("Delete"));
    m_btnImport = new wxButton(this, wxID_BTN_IMPORT, wxT("Import"));
    m_btnSaveLayout = new wxButton(this, wxID_BTN_SAVE_LAYOUT, wxT("Save Layout"));
    label_1 = new wxStaticText(this, wxID_ANY, wxT("Directory"));
    m_txtWorkflowsFolder = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_READONLY);

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(coreWorkflowManagerWidgetUI, wxDialog)
    // begin wxGlade: coreWorkflowManagerWidgetUI::event_table
    EVT_TREE_ITEM_ACTIVATED(wxID_TREE_WORKFLOWS, coreWorkflowManagerWidgetUI::OnItemActivated)
    EVT_BUTTON(wxID_BTN_NEW, coreWorkflowManagerWidgetUI::OnBtnNew)
    EVT_BUTTON(wxID_BTN_EDIT, coreWorkflowManagerWidgetUI::OnBtnEdit)
    EVT_BUTTON(wxID_BTN_RENAME, coreWorkflowManagerWidgetUI::OnBtnRename)
    EVT_BUTTON(wxID_BTN_ACTIVATE, coreWorkflowManagerWidgetUI::OnBtnActivate)
    EVT_BUTTON(wxID_BTN_DELETE, coreWorkflowManagerWidgetUI::OnBtnDelete)
    EVT_BUTTON(wxID_BTN_IMPORT, coreWorkflowManagerWidgetUI::OnBtnImport)
    EVT_BUTTON(wxID_BTN_SAVE_LAYOUT, coreWorkflowManagerWidgetUI::OnBtnSaveLayout)
    // end wxGlade
END_EVENT_TABLE();


void coreWorkflowManagerWidgetUI::OnItemActivated(wxTreeEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (coreWorkflowManagerWidgetUI::OnItemActivated) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void coreWorkflowManagerWidgetUI::OnBtnNew(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (coreWorkflowManagerWidgetUI::OnBtnNew) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void coreWorkflowManagerWidgetUI::OnBtnEdit(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (coreWorkflowManagerWidgetUI::OnBtnEdit) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void coreWorkflowManagerWidgetUI::OnBtnRename(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (coreWorkflowManagerWidgetUI::OnBtnRename) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void coreWorkflowManagerWidgetUI::OnBtnActivate(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (coreWorkflowManagerWidgetUI::OnBtnActivate) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void coreWorkflowManagerWidgetUI::OnBtnDelete(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (coreWorkflowManagerWidgetUI::OnBtnDelete) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void coreWorkflowManagerWidgetUI::OnBtnImport(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (coreWorkflowManagerWidgetUI::OnBtnImport) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void coreWorkflowManagerWidgetUI::OnBtnSaveLayout(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (coreWorkflowManagerWidgetUI::OnBtnSaveLayout) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


// wxGlade: add coreWorkflowManagerWidgetUI event handlers


void coreWorkflowManagerWidgetUI::set_properties()
{
    // begin wxGlade: coreWorkflowManagerWidgetUI::set_properties
    SetTitle(wxT("Workflow Manager"));
    SetSize(wxSize(514, 405));
    m_btnSaveLayout->SetMinSize(wxSize(90, 23));
    m_btnSaveLayout->SetToolTip(wxT("Save active workflow layout from current GUI widgets"));
    // end wxGlade
}


void coreWorkflowManagerWidgetUI::do_layout()
{
    // begin wxGlade: coreWorkflowManagerWidgetUI::do_layout
    wxBoxSizer* sizer_6 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_7 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_6_copy = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxVERTICAL);
    sizer_6->Add(m_bmpBitmap, 0, wxEXPAND, 0);
    sizer_6_copy->Add(m_treeWorkflows, 1, wxALL|wxEXPAND, 5);
    sizer_2->Add(m_btnNew, 0, wxALL|wxEXPAND, 5);
    sizer_2->Add(m_btnEdit, 0, wxALL|wxEXPAND, 5);
    sizer_2->Add(m_btnRename, 0, wxALL|wxEXPAND, 5);
    sizer_2->Add(m_btnActivate, 0, wxALL|wxEXPAND, 5);
    sizer_2->Add(m_btnDelete, 0, wxALL|wxEXPAND, 5);
    sizer_2->Add(m_btnImport, 0, wxALL|wxEXPAND, 5);
    sizer_2->Add(m_btnSaveLayout, 0, wxALL|wxEXPAND, 5);
    sizer_6_copy->Add(sizer_2, 0, wxALL|wxEXPAND, 5);
    sizer_6->Add(sizer_6_copy, 1, wxEXPAND, 0);
    sizer_7->Add(label_1, 0, 0, 0);
    sizer_7->Add(m_txtWorkflowsFolder, 1, 0, 0);
    sizer_6->Add(sizer_7, 0, wxALL|wxEXPAND, 5);
    SetSizer(sizer_6);
    Layout();
    // end wxGlade
}

