// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Oct 01 14:37:23 2010

#include <wx/wx.h>
#include <wx/image.h>

#ifndef COREWORKFLOWMANAGERWIDGETUI_H
#define COREWORKFLOWMANAGERWIDGETUI_H

// begin wxGlade: ::dependencies
#include <wx/treectrl.h>
// end wxGlade

// begin wxGlade: ::extracode
#include "wxID.h"

#define wxID_BTN_NEW wxID( "wxID_BTN_NEW" )
#define wxID_BTN_DELETE wxID( "wxID_BTN_DELETE" )
#define wxID_BTN_EDIT wxID( "wxID_BTN_EDIT" )
#define wxID_BTN_RENAME wxID( "wxID_BTN_RENAME" )
#define wxID_BTN_ACTIVATE wxID( "wxID_BTN_ACTIVATE" )
#define wxID_TREE_WORKFLOWS wxID( "wxID_TREE_WORKFLOWS" )
#define wxID_BTN_IMPORT wxID( "wxID_BTN_IMPORT" )
#define wxID_BTN_SAVE_LAYOUT wxID( "wxID_BTN_SAVE_LAYOUT" )

class wxTreeCtrlWorkflows : public wxTreeCtrl
{
public:
	wxTreeCtrlWorkflows(wxWindow*  parent, wxWindowID id, const wxPoint&  pos = wxDefaultPosition, const wxSize&  size = wxDefaultSize, long style = wxTR_HAS_BUTTONS, const wxValidator&  validator = wxDefaultValidator, const wxString&  name = "treeCtrl")
		: wxTreeCtrl( parent, id, pos, size, style | wxTR_EDIT_LABELS, validator, name )
	{

	}
};



// end wxGlade


class coreWorkflowManagerWidgetUI: public wxDialog {
public:
    // begin wxGlade: coreWorkflowManagerWidgetUI::ids
    // end wxGlade

    coreWorkflowManagerWidgetUI(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: coreWorkflowManagerWidgetUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: coreWorkflowManagerWidgetUI::attributes
    wxStaticBitmap* m_bmpBitmap;
    wxTreeCtrlWorkflows* m_treeWorkflows;
    wxButton* m_btnNew;
    wxButton* m_btnEdit;
    wxButton* m_btnRename;
    wxButton* m_btnActivate;
    wxButton* m_btnDelete;
    wxButton* m_btnImport;
    wxButton* m_btnSaveLayout;
    wxStaticText* label_1;
    wxTextCtrl* m_txtWorkflowsFolder;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnItemActivated(wxTreeEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnNew(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnEdit(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnRename(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnActivate(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnDelete(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnImport(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnSaveLayout(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // COREWORKFLOWMANAGERWIDGETUI_H
