// -*- C++ -*- generated by wxGlade 0.6.3 on Wed Aug 26 17:55:39 2009

#include "ptRadiographVisualizationWidgetUI.h"

// begin wxGlade: ::extracode

// end wxGlade


ptRadiographVisualizationWidgetUI::ptRadiographVisualizationWidgetUI(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: ptRadiographVisualizationWidgetUI::ptRadiographVisualizationWidgetUI
    m_lblParam1 = new wxStaticText(this, wxID_ANY, wxT("param1"));
    m_txtParam1 = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
//    m_window = new CustomWidget(this, wxID_ANY);
    m_btnProject = new wxButton(this, wxID_ANY, wxT("Show Projection"));

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(ptRadiographVisualizationWidgetUI, wxPanel)
    // begin wxGlade: ptRadiographVisualizationWidgetUI::event_table
    EVT_BUTTON(wxID_ANY, ptRadiographVisualizationWidgetUI::OnBtnShowProjection)
    // end wxGlade
END_EVENT_TABLE();


void ptRadiographVisualizationWidgetUI::OnBtnShowProjection(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (ptRadiographVisualizationWidgetUI::OnBtnShowProjection) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


// wxGlade: add ptRadiographVisualizationWidgetUI event handlers


void ptRadiographVisualizationWidgetUI::set_properties()
{
    // begin wxGlade: ptRadiographVisualizationWidgetUI::set_properties
    //SetScrollRate(10, 10);
    // end wxGlade
}


void ptRadiographVisualizationWidgetUI::do_layout()
{
    // begin wxGlade: ptRadiographVisualizationWidgetUI::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    sizer_2->Add(m_lblParam1, 1, 0, 1);
    sizer_2->Add(m_txtParam1, 0, 0, 1);
    sizer_1->Add(sizer_2, 0, wxEXPAND, 1);
    sizer_1->Add(10, 10, 0, 0, 0);
//    sizer_1->Add(m_window, 1, wxEXPAND, 0);
    sizer_1->Add(m_btnProject, 0, wxALIGN_RIGHT, 0);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    // end wxGlade
}

