/*
* Copyright (c) 2009,
* Computational Image and Simulation Technologies in Biomedicine (CISTIB),
* Universitat Pompeu Fabra (UPF), Barcelona, Spain. All rights reserved.
* See license.txt file for details.
*/

// -*- C++ -*- generated by wxGlade 0.6.3 on Tue May 13 18:11:24 2008

#include "coreImageWidgetUI.h"

// begin wxGlade: ::extracode
// end wxGlade



ImageWidgetUI::ImageWidgetUI(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: ImageWidgetUI::ImageWidgetUI
    sizer_3_staticbox = new wxStaticBox(this, -1, wxT("Image Information"));
    txtCoordinates = new wxStaticText(this, wxID_ANY, wxT("Coordinates"));
    leCoordinates = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_READONLY);
    txtIntensity = new wxStaticText(this, wxID_ANY, wxT("Intensity"));
    leIntensity = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_READONLY);

    set_properties();
    do_layout();
    // end wxGlade
}


void ImageWidgetUI::set_properties()
{
    // begin wxGlade: ImageWidgetUI::set_properties
    // end wxGlade
}


void ImageWidgetUI::do_layout()
{
    // begin wxGlade: ImageWidgetUI::do_layout
    wxStaticBoxSizer* sizer_3 = new wxStaticBoxSizer(sizer_3_staticbox, wxVERTICAL);
    wxBoxSizer* sizer_5 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxHORIZONTAL);
    sizer_4->Add(txtCoordinates, 2, wxALIGN_CENTER_VERTICAL, 0);
    sizer_4->Add(leCoordinates, 4, wxEXPAND|wxALIGN_CENTER_VERTICAL, 0);
    sizer_3->Add(sizer_4, 0, wxEXPAND, 0);
    sizer_5->Add(txtIntensity, 2, wxALIGN_CENTER_VERTICAL, 0);
    sizer_5->Add(leIntensity, 4, wxALIGN_CENTER_VERTICAL, 0);
    sizer_3->Add(sizer_5, 0, wxEXPAND, 0);
    SetSizer(sizer_3);
    sizer_3->Fit(this);
    // end wxGlade
	sizer_3_staticbox->SetFont(wxFont(8, wxDEFAULT, wxNORMAL, wxBOLD, 0, wxT("")));
}

