/*
* Copyright (c) 2009,
* Computational Image and Simulation Technologies in Biomedicine (CISTIB),
* Universitat Pompeu Fabra (UPF), Barcelona, Spain. All rights reserved.
* See license.txt file for details.
*/

// -*- C++ -*- generated by wxGlade 0.6.3 on Tue May 13 18:11:24 2008

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade

#include "gmWidgetsWin32Header.h"

#ifndef COREIMAGEWIDGETUI_H
#define COREIMAGEWIDGETUI_H


// begin wxGlade: ::extracode
// end wxGlade

/** 
\brief 
\ingroup gmWidgets
\author 
\date 
*/
class PLUGIN_EXPORT ImageWidgetUI: public wxPanel {
public:
    // begin wxGlade: ImageWidgetUI::ids
    // end wxGlade

    ImageWidgetUI(
		wxWindow* parent, 
		int id, 
		const wxPoint& pos=wxDefaultPosition, 
		const wxSize& size=wxDefaultSize, 
		long style=0);

private:
    // begin wxGlade: ImageWidgetUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: ImageWidgetUI::attributes
    wxStaticBox* sizer_3_staticbox;
    wxStaticText* txtCoordinates;
    wxTextCtrl* leCoordinates;
    wxStaticText* txtIntensity;
    wxTextCtrl* leIntensity;
    // end wxGlade
}; // wxGlade: end class


#endif // COREIMAGEWIDGETUI_H
