/*
* Copyright (c) 2009,
* Computational Image and Simulation Technologies in Biomedicine (CISTIB),
* Universitat Pompeu Fabra (UPF), Barcelona, Spain. All rights reserved.
* See license.txt file for details.
*/

#ifndef _SandboxPluginSubtractPanelWidget_H
#define _SandboxPluginSubtractPanelWidget_H

#include "SandboxPluginSubtractProcessor.h"
#include "SandboxPluginSubtractPanelWidgetUI.h"
#include "coreProcessingWidget.h"

// CoreLib
#include "coreProcessorOutputObserver.h"

// GuiBridgeLib
#include "gblWxConnectorOfWidgetChangesToSlotFunction.h"

namespace Core{ namespace Widgets {
	class UserHelper;
	class DataEntityListBrowser;
}}
	
namespace SandboxPlugin{

/**
PanelWidget for interacting with SandboxPlugin::SubtractProcessor.

The parent class SandboxPluginSubtractPanelWidgetUI contains all the code for 
buttons, labels, layouts, etc.

The SubtractPanelWidget provides the functions that handle the GUI events 
generated by SandboxPluginSubtractPanelWidgetUI (see for example the function 
OnBtnSub).

SandboxPluginSubtractPanelWidgetUI is created with wxGlade, a graphical 
GUI editor. It is encouraged to use wxGlade for designing your widgets.

\note In Gimias there's several PanelWidgets for different processors in 
different plugins. All the panel widgets are disabled except the active one that will be 
enabled ( Enable() ). The active one is the one that the user clicked.
If you need to catch the event when this panel widget is enabled or disabled
overwrite the function Enable( ). Be carefull when you call Enable( true ) to 
this widget because the behaviour will be unpredicted.

\ingroup SandboxPlugin
\author Berta Marti
\date 24 oct 2008
*/
class SubtractPanelWidget : 
	public SandboxPluginSubtractPanelWidgetUI,
	public Core::Widgets::ProcessingWidget
{

// OPERATIONS
public:
	//!
	coreDefineBaseWindowFactory( SubtractPanelWidget )

	//!
	SubtractPanelWidget( wxWindow* parent, int id = wxID_ANY, const wxPoint&  pos = wxDefaultPosition, const wxSize&  size = wxDefaultSize, long style = 0);

	//!
	~SubtractPanelWidget( );

	//! Add button events to the bridge and call UpdateWidget()
	void OnInit( );
	
	//!
	bool Enable( bool enable /*= true */ );

	//!
	Core::BaseProcessor::Pointer GetProcessor( );

private:
	DECLARE_EVENT_TABLE()

	//! Update GUI from working data
	void UpdateWidget();

	//! Update working data from GUI
	void UpdateData();

	//! Validate GUI data
	bool Validate();

	//! Button has been pressed
	void OnBtnApply(wxCommandEvent& event);

	//!
	void UpdateHelperWidget( );

	//!
	void OnModifiedInput( int num );

	
// ATTRIBUTES
private:
	//! Working data of the processor
	SubtractProcessor::Pointer m_Processor;

	//! Each time a text control is modified, UpdateData( ) will be called
	gbl::wx::ConnectorOfWidgetChangesToSlotFunction m_changeInWidgetObserver;
};

} //namespace SandboxPlugin{

#endif //_SandboxPluginSubtractPanelWidget_H
