// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Oct 24 09:55:28 2008

#include <wx/wx.h>
#include <wx/image.h>
#include "wxID.h"

#ifndef _SandboxPluginSubtractPanelWidgetUI_H
#define _SandboxPluginSubtractPanelWidgetUI_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade

//define id for widget controls
#define wxID_BTN_SUBTRACT wxID("SandboxPluginSubtractPanelWidgetUIBtnSub")


class SandboxPluginSubtractPanelWidgetUI: public wxScrolledWindow {
public:
    // begin wxGlade: SandboxPluginSubtractPanelWidgetUI::ids
    // end wxGlade

    SandboxPluginSubtractPanelWidgetUI(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    // begin wxGlade: SandboxPluginSubtractPanelWidgetUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: SandboxPluginSubtractPanelWidgetUI::attributes
    wxStaticBox* sizer_1_staticbox;
    wxButton* m_btnSubtract;
    // end wxGlade
}; // wxGlade: end class


#endif // _SandboxPluginSubtractPanelWidgetUI_H
