// -*- C++ -*- generated by wxGlade 0.6.3 on Tue Apr 27 10:34:16 2010

#include "svConfigurationWidgetUI.h"

// begin wxGlade: ::extracode

// end wxGlade


svConfigurationWidgetUI::svConfigurationWidgetUI(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: svConfigurationWidgetUI::svConfigurationWidgetUI
    sizer_1_staticbox = new wxStaticBox(this, -1, wxT("Time Window parameters"));
    label_2 = new wxStaticText(this, wxID_ANY, wxT("Offset"), wxDefaultPosition, wxDefaultSize, wxALIGN_CENTRE);
    m_txtOffset = new wxTextCtrl(this, wxID_SIGNAL_OFFSET , wxEmptyString);
    label_3 = new wxStaticText(this, wxID_ANY, wxT("Size"), wxDefaultPosition, wxDefaultSize, wxALIGN_CENTRE);
    m_txtSize = new wxTextCtrl(this, wxID_SIGNAL_WINDOW_SIZE, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(svConfigurationWidgetUI, wxPanel)
    // begin wxGlade: svConfigurationWidgetUI::event_table
    EVT_TEXT(wxID_SIGNAL_OFFSET , svConfigurationWidgetUI::OnOffset)
    EVT_TEXT(wxID_SIGNAL_WINDOW_SIZE, svConfigurationWidgetUI::OnSize)
    // end wxGlade
END_EVENT_TABLE();


void svConfigurationWidgetUI::OnOffset(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (svConfigurationWidgetUI::OnOffset) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void svConfigurationWidgetUI::OnSize(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (svConfigurationWidgetUI::OnSize) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


// wxGlade: add svConfigurationWidgetUI event handlers


void svConfigurationWidgetUI::set_properties()
{
    // begin wxGlade: svConfigurationWidgetUI::set_properties
    // end wxGlade
}


void svConfigurationWidgetUI::do_layout()
{
    // begin wxGlade: svConfigurationWidgetUI::do_layout
    wxStaticBoxSizer* sizer_1 = new wxStaticBoxSizer(sizer_1_staticbox, wxVERTICAL);
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxHORIZONTAL);
    sizer_3->Add(label_2, 1, wxEXPAND, 0);
    sizer_3->Add(m_txtOffset, 1, 0, 0);
    sizer_1->Add(sizer_3, 0, wxEXPAND, 0);
    sizer_4->Add(label_3, 1, wxEXPAND, 0);
    sizer_4->Add(m_txtSize, 1, 0, 0);
    sizer_1->Add(sizer_4, 0, wxEXPAND, 0);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    // end wxGlade
}

