// -*- C++ -*- generated by wxGlade 0.6.3 on Wed Jan 20 14:28:14 2010

#include "svPlotFilterAnnotationsWidgetUI.h"

// begin wxGlade: ::extracode

// end wxGlade


svPlotFilterAnnotationsWidgetUI::svPlotFilterAnnotationsWidgetUI(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxScrolledWindow(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: svPlotFilterAnnotationsWidgetUI::svPlotFilterAnnotationsWidgetUI
    sizer_1_staticbox = new wxStaticBox(this, -1, wxT("Filter Annotations"));
    m_TreeCtrl = new wxTreeCtrl(this, wxID_PLOT_FILTER_ANNOTATIONS_TREE, wxDefaultPosition, wxDefaultSize, wxTR_HAS_BUTTONS|wxTR_DEFAULT_STYLE|wxSUNKEN_BORDER);

    set_properties();
    do_layout();
    // end wxGlade
}


void svPlotFilterAnnotationsWidgetUI::set_properties()
{
    // begin wxGlade: svPlotFilterAnnotationsWidgetUI::set_properties
    SetScrollRate(10, 10);
    // end wxGlade
}


void svPlotFilterAnnotationsWidgetUI::do_layout()
{
    // begin wxGlade: svPlotFilterAnnotationsWidgetUI::do_layout
    wxStaticBoxSizer* sizer_1 = new wxStaticBoxSizer(sizer_1_staticbox, wxVERTICAL);
    sizer_1->Add(m_TreeCtrl, 1, wxEXPAND, 0);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    // end wxGlade
}

