// -*- C++ -*- generated by wxGlade 0.6.3 on Tue Apr 27 08:20:49 2010

#include "svPlotWidgetUI.h"

// begin wxGlade: ::extracode

// end wxGlade


svPlotWidgetUI::svPlotWidgetUI(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: svPlotWidgetUI::svPlotWidgetUI
    m_plotNotebook = new wxNotebook(this, wxID_PLOTNOTEBOOK, wxDefaultPosition, wxDefaultSize, 0);
    ploteNotebookePane1 = new wxPanel(m_plotNotebook, wxID_ANY);

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(svPlotWidgetUI, wxPanel)
    // begin wxGlade: svPlotWidgetUI::event_table
    EVT_NOTEBOOK_PAGE_CHANGED(wxID_PLOTNOTEBOOK, svPlotWidgetUI::OnPageChanged)
    // end wxGlade
END_EVENT_TABLE();


void svPlotWidgetUI::OnPageChanged(wxNotebookEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (svPlotWidgetUI::OnPageChanged) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


// wxGlade: add svPlotWidgetUI event handlers


void svPlotWidgetUI::set_properties()
{
    // begin wxGlade: svPlotWidgetUI::set_properties
    // end wxGlade
}


void svPlotWidgetUI::do_layout()
{
    // begin wxGlade: svPlotWidgetUI::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    ploteNotebookePane1->SetSizer(sizer_2);
    m_plotNotebook->AddPage(ploteNotebookePane1, wxT("tab1"));
    sizer_4->Add(m_plotNotebook, 1, wxEXPAND, 0);
    sizer_1->Add(sizer_4, 1, wxEXPAND, 0);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    // end wxGlade
}

