// -*- C++ -*- generated by wxGlade 0.6.3 on Wed Jun 09 14:34:09 2010

#include <wx/wx.h>
#include <wx/image.h>

#ifndef SVSIGNALFREEANNOTATIONDIALOGUI_H
#define SVSIGNALFREEANNOTATIONDIALOGUI_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#define wxID_ANNOTATION_NAME wxID( "wxID_ANNOTATION_NAME" )

// end wxGlade


class svSignalFreeAnnotationDialogUI: public wxDialog {
public:
    // begin wxGlade: svSignalFreeAnnotationDialogUI::ids
    // end wxGlade

    svSignalFreeAnnotationDialogUI(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: svSignalFreeAnnotationDialogUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: svSignalFreeAnnotationDialogUI::attributes
    wxTextCtrl* m_txtName;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnTextEnter(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // SVSIGNALFREEANNOTATIONDIALOGUI_H
