// -*- C++ -*- generated by wxGlade 0.6.3 on Wed Jun 09 14:34:09 2010

#include "svSignalFreeAnnotationDialogUI.h"

// begin wxGlade: ::extracode

// end wxGlade


svSignalFreeAnnotationDialogUI::svSignalFreeAnnotationDialogUI(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxRESIZE_BORDER|wxTHICK_FRAME)
{
    // begin wxGlade: svSignalFreeAnnotationDialogUI::svSignalFreeAnnotationDialogUI
    m_txtName = new wxTextCtrl(this, wxID_ANNOTATION_NAME, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(svSignalFreeAnnotationDialogUI, wxDialog)
    // begin wxGlade: svSignalFreeAnnotationDialogUI::event_table
    EVT_TEXT_ENTER(wxID_ANNOTATION_NAME, svSignalFreeAnnotationDialogUI::OnTextEnter)
    // end wxGlade
END_EVENT_TABLE();


void svSignalFreeAnnotationDialogUI::OnTextEnter(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (svSignalFreeAnnotationDialogUI::OnTextEnter) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


// wxGlade: add svSignalFreeAnnotationDialogUI event handlers


void svSignalFreeAnnotationDialogUI::set_properties()
{
    // begin wxGlade: svSignalFreeAnnotationDialogUI::set_properties
    SetTitle(wxT("dialog_1"));
    // end wxGlade
}


void svSignalFreeAnnotationDialogUI::do_layout()
{
    // begin wxGlade: svSignalFreeAnnotationDialogUI::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    sizer_1->Add(m_txtName, 0, wxEXPAND, 0);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    Layout();
    // end wxGlade
}

