// -*- C++ -*- generated by wxGlade 0.6.3 on Tue Mar 18 16:56:29 2008

#include "GuiBridgeLibWxWidgetsTestApp.h"
#include <iostream>

// begin wxGlade: ::extracode
// end wxGlade

MainFrame::MainFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: MainFrame::MainFrame
    text_ctrl_1 = new wxTextCtrl(this, wxID_ANY, wxT("One"), wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
    radio_btn_1 = new wxRadioButton(this, wxID_ANY, wxT("radio_btn_1"));
    radio_btn_2 = new wxRadioButton(this, wxID_ANY, wxT("radio_btn_2"));
    button_1 = new wxToggleButton(this, wxID_ANY, wxT("button_1"));
    checkbox_1 = new wxCheckBox(this, wxID_ANY, wxT("checkbox_1"));
    const wxString choice_1_choices[] = {
        wxT("One"),
        wxT("Two")
    };
    choice_1 = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 2, choice_1_choices, 0);
    const wxString combo_box_1_choices[] = {
        wxT("One"),
        wxT("Two")
    };
    combo_box_1 = new wxComboBox(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, 2, combo_box_1_choices, wxCB_DROPDOWN);
    const wxString list_box_1_choices[] = {
        wxT("One"),
        wxT("Two")
    };
    list_box_1 = new wxListBox(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 2, list_box_1_choices, 0);
    btnTest = new wxButton(this, wxID_ANY, wxT("Test!"));

    set_properties();
    do_layout();
    // end wxGlade

	using namespace gbl::wx;
	m_Connector = ConnectorOfWidgetChangesToSlotFunctionPtr(new ConnectorOfWidgetChangesToSlotFunction);
	m_Connector->SetSlotFunction(this, &MainFrame::UpdateWidget);
	m_Connector->Observe(this->text_ctrl_1);
	m_Connector->Observe(this->radio_btn_1);
	m_Connector->Observe(this->radio_btn_2);
	m_Connector->Observe(this->button_1);
	m_Connector->Observe(this->checkbox_1);
	m_Connector->Observe(this->list_box_1);
	m_Connector->Observe(this->combo_box_1);
	m_Connector->Observe(this->choice_1);

	gbl::SetText(this->list_box_1, "Two");
	gbl::SetText(this->combo_box_1, "One");
}


BEGIN_EVENT_TABLE(MainFrame, wxFrame)
// content of this block not found: did you rename this class?
END_EVENT_TABLE();

void MainFrame::set_properties()
{
    // begin wxGlade: MainFrame::set_properties
    SetTitle(wxT("frame_1"));
    choice_1->SetSelection(0);
    combo_box_1->SetSelection(-1);
    list_box_1->SetSelection(0);
    // end wxGlade
}


void MainFrame::do_layout()
{
    // begin wxGlade: MainFrame::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    sizer_1->Add(text_ctrl_1, 0, 0, 0);
    sizer_2->Add(radio_btn_1, 0, 0, 0);
    sizer_2->Add(radio_btn_2, 0, 0, 0);
    sizer_1->Add(sizer_2, 1, wxEXPAND, 0);
    sizer_1->Add(button_1, 0, 0, 0);
    sizer_1->Add(checkbox_1, 0, 0, 0);
    sizer_1->Add(choice_1, 0, 0, 0);
    sizer_1->Add(combo_box_1, 0, 0, 0);
    sizer_1->Add(list_box_1, 0, 0, 0);
    sizer_1->Add(btnTest, 0, wxEXPAND, 0);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    Layout();
    // end wxGlade
}

void MainFrame::UpdateWidget()
{
	std::cout << "MainFrame::UpdateWidget()\n";
}

void MainFrame::TestBridgeEvent()
{
	std::cout << gbl::GetText(this->text_ctrl_1) << " text_ctrl_1\n";
	std::cout << gbl::GetText(this->radio_btn_1) << " radio_btn_1\n";
	std::cout << gbl::GetText(this->radio_btn_2) << " radio_btn_2\n";
	std::cout << gbl::GetText(this->button_1) << " toggle button_1\n";
	std::cout << gbl::GetText(this->checkbox_1) << " checkbox_1\n";
	std::cout << gbl::GetNumber(this->list_box_1) << " toggle list_box_1\n";
	std::cout << gbl::GetNumber(this->combo_box_1) << " toggle combo_box_1\n";
	std::cout << gbl::GetNumber(this->choice_1) << " choice_1\n";
}

class MyApp: public wxApp {
public:
    bool OnInit();
};

IMPLEMENT_APP_CONSOLE(MyApp)

bool MyApp::OnInit()
{
    wxInitAllImageHandlers();
    MainFrame* frame_1 = new MainFrame(NULL, wxID_ANY, wxEmptyString);
    SetTopWindow(frame_1);
    frame_1->Show();
    return true;
}






