// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Mar 11 11:53:44 2010

#include <wx/wx.h>
#include <wx/image.h>

#ifndef WXMITKVIEWCONFIGURATIONUI_H
#define WXMITKVIEWCONFIGURATIONUI_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#include "wxID.h"
#define wxID_RDBX_ROTATE wxID( "wxID_RDBX_ROTATE" )
#define wxID_VIEW_CHK_FLIP wxID( "wxID_VIEW_CHK_FLIP" )
#define wxID_VIEW_CMB_DIRECTION wxID( "wxID_VIEW_CMB_DIRECTION" )

// end wxGlade


class wxMitkViewConfigurationUI: public wxPanel {
public:
    // begin wxGlade: wxMitkViewConfigurationUI::ids
    // end wxGlade

    wxMitkViewConfigurationUI(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    // begin wxGlade: wxMitkViewConfigurationUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: wxMitkViewConfigurationUI::attributes
    wxStaticText* Direction;
    wxComboBox* m_cmbDirection;
    wxCheckBox* m_chkFlip;
    wxRadioBox* m_rdbxRotate;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnDirection(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnFlip(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnRotate(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // WXMITKVIEWCONFIGURATIONUI_H
