// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Aug 26 11:59:27 2010

#include <wx/wx.h>
#include <wx/image.h>

#ifndef WXMITKMULTIRENDERWINDOWCONFIGUI_H
#define WXMITKMULTIRENDERWINDOWCONFIGUI_H

// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade

// begin wxGlade: ::extracode
#include "wxMitkViewConfiguration.h"
#include "wxID.h"
#define wxID_CMB_CURRENT_VIEW wxID( "wxID_CMB_CURRENT_VIEW" )
#define wxID_APPLY_TO_ALL wxID( "wxID_APPLY_TO_ALL" )
#define wxID_NUMBER_OF_SLICES wxID( "wxID_NUMBER_OF_SLICES" )

// end wxGlade


class wxMitkMultiRenderWindowConfigUI: public wxScrolledWindow {
public:
    // begin wxGlade: wxMitkMultiRenderWindowConfigUI::ids
    // end wxGlade

    wxMitkMultiRenderWindowConfigUI(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    // begin wxGlade: wxMitkMultiRenderWindowConfigUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: wxMitkMultiRenderWindowConfigUI::attributes
    wxStaticBox* sizer_4_staticbox;
    wxStaticBox* sizer_3_staticbox;
    wxStaticBox* sizer_5_staticbox;
    wxStaticText* label_1;
    wxSpinCtrl* m_spinNumberOfSlices;
    wxCheckBox* m_chkApplyToAll;
    wxComboBox* m_cmbCurrentView;
    mitk::wxMitkViewConfiguration* m_ViewConfig;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnNumberOfSlices(wxSpinEvent &event); // wxGlade: <event_handler>
    virtual void OnApplyAll(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnSelectedView(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // WXMITKMULTIRENDERWINDOWCONFIGUI_H
