// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Aug 26 11:59:27 2010

#include "wxMitkMultiRenderWindowConfigUI.h"

// begin wxGlade: ::extracode

// end wxGlade


wxMitkMultiRenderWindowConfigUI::wxMitkMultiRenderWindowConfigUI(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxScrolledWindow(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: wxMitkMultiRenderWindowConfigUI::wxMitkMultiRenderWindowConfigUI
    sizer_3_staticbox = new wxStaticBox(this, -1, wxT("Current SliceView"));
    sizer_4_staticbox = new wxStaticBox(this, -1, wxT("View configuration"));
    sizer_5_staticbox = new wxStaticBox(this, -1, wxT("Parameters"));
    label_1 = new wxStaticText(this, wxID_ANY, wxT("Number of slices"));
    m_spinNumberOfSlices = new wxSpinCtrl(this, wxID_NUMBER_OF_SLICES, wxT(""), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 100);
    m_chkApplyToAll = new wxCheckBox(this, wxID_APPLY_TO_ALL , wxT("Apply to all"));
    const wxString *m_cmbCurrentView_choices = NULL;
    m_cmbCurrentView = new wxComboBox(this, wxID_CMB_CURRENT_VIEW , wxT(""), wxDefaultPosition, wxDefaultSize, 0, m_cmbCurrentView_choices, wxCB_DROPDOWN|wxCB_READONLY);
    m_ViewConfig = new mitk::wxMitkViewConfiguration(this, wxID_ANY);

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(wxMitkMultiRenderWindowConfigUI, wxScrolledWindow)
    // begin wxGlade: wxMitkMultiRenderWindowConfigUI::event_table
    EVT_SPINCTRL(wxID_NUMBER_OF_SLICES, wxMitkMultiRenderWindowConfigUI::OnNumberOfSlices)
    EVT_CHECKBOX(wxID_APPLY_TO_ALL , wxMitkMultiRenderWindowConfigUI::OnApplyAll)
    EVT_TEXT(wxID_CMB_CURRENT_VIEW , wxMitkMultiRenderWindowConfigUI::OnSelectedView)
    // end wxGlade
END_EVENT_TABLE();


void wxMitkMultiRenderWindowConfigUI::OnNumberOfSlices(wxSpinEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (wxMitkMultiRenderWindowConfigUI::OnNumberOfSlices) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void wxMitkMultiRenderWindowConfigUI::OnApplyAll(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (wxMitkMultiRenderWindowConfigUI::OnApplyAll) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void wxMitkMultiRenderWindowConfigUI::OnSelectedView(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (wxMitkMultiRenderWindowConfigUI::OnSelectedView) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


// wxGlade: add wxMitkMultiRenderWindowConfigUI event handlers


void wxMitkMultiRenderWindowConfigUI::set_properties()
{
    // begin wxGlade: wxMitkMultiRenderWindowConfigUI::set_properties
    SetSize(wxSize(250, 373));
    SetScrollRate(10, 10);
    m_chkApplyToAll->SetValue(1);
    // end wxGlade
}


void wxMitkMultiRenderWindowConfigUI::do_layout()
{
    // begin wxGlade: wxMitkMultiRenderWindowConfigUI::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxStaticBoxSizer* sizer_4 = new wxStaticBoxSizer(sizer_4_staticbox, wxHORIZONTAL);
    wxStaticBoxSizer* sizer_3 = new wxStaticBoxSizer(sizer_3_staticbox, wxHORIZONTAL);
    wxStaticBoxSizer* sizer_5 = new wxStaticBoxSizer(sizer_5_staticbox, wxVERTICAL);
    wxGridSizer* grid_sizer_1 = new wxGridSizer(2, 2, 2, 2);
    grid_sizer_1->Add(label_1, 0, wxALIGN_CENTER_VERTICAL, 0);
    grid_sizer_1->Add(m_spinNumberOfSlices, 0, 0, 0);
    grid_sizer_1->Add(m_chkApplyToAll, 0, wxALL, 0);
    sizer_5->Add(grid_sizer_1, 1, wxEXPAND, 0);
    sizer_1->Add(sizer_5, 0, wxEXPAND, 0);
    sizer_3->Add(m_cmbCurrentView, 1, wxEXPAND, 0);
    sizer_1->Add(sizer_3, 0, wxEXPAND, 0);
    sizer_4->Add(m_ViewConfig, 1, wxEXPAND, 0);
    sizer_1->Add(sizer_4, 0, wxEXPAND, 0);
    SetSizer(sizer_1);
    // end wxGlade
}

