// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Jul 01 11:35:34 2010

#include "coreImageContrastWidgetUI.h"

// begin wxGlade: ::extracode

// end wxGlade


coreImageContrastWidgetUI::coreImageContrastWidgetUI(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxScrolledWindow(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: coreImageContrastWidgetUI::coreImageContrastWidgetUI
    m_checkEnable = new wxCheckBox(this, wxID_EnableSliders, wxT("Enable Sliders"));
    m_bmpAdd = new wxStaticBitmap(this, wxID_ANY, wxNullBitmap);
    negativeSlider = new wxSlider(this, wxID_NegativeSlider, 0, 0, 100, wxDefaultPosition, wxDefaultSize, wxSL_INVERSE);
    m_bmpSubstract = new wxStaticBitmap(this, wxID_ANY, wxNullBitmap);
    positiveSlider = new wxSlider(this, wxID_PositiveSlider, 0, 0, 100, wxDefaultPosition, wxDefaultSize, wxSL_INVERSE);

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(coreImageContrastWidgetUI, wxScrolledWindow)
    // begin wxGlade: coreImageContrastWidgetUI::event_table
    EVT_CHECKBOX(wxID_EnableSliders, coreImageContrastWidgetUI::OnChkBoxEnable)
    EVT_COMMAND_SCROLL(wxID_NegativeSlider, coreImageContrastWidgetUI::OnSliderNegativeContrast)
    EVT_COMMAND_SCROLL(wxID_PositiveSlider, coreImageContrastWidgetUI::OnSliderPositiveContrast)
    // end wxGlade
END_EVENT_TABLE();


void coreImageContrastWidgetUI::OnChkBoxEnable(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (coreImageContrastWidgetUI::OnChkBoxEnable) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void coreImageContrastWidgetUI::OnSliderNegativeContrast(wxScrollEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (coreImageContrastWidgetUI::OnSliderNegativeContrast) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void coreImageContrastWidgetUI::OnSliderPositiveContrast(wxScrollEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (coreImageContrastWidgetUI::OnSliderPositiveContrast) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


// wxGlade: add coreImageContrastWidgetUI event handlers


void coreImageContrastWidgetUI::set_properties()
{
    // begin wxGlade: coreImageContrastWidgetUI::set_properties
    SetSize(wxSize(368, 134));
    SetScrollRate(10, 10);
    // end wxGlade
}


void coreImageContrastWidgetUI::do_layout()
{
    // begin wxGlade: coreImageContrastWidgetUI::do_layout
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_6 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_5 = new wxBoxSizer(wxHORIZONTAL);
    sizer_3->Add(m_checkEnable, 0, 0, 0);
    sizer_5->Add(m_bmpAdd, 0, wxALIGN_RIGHT, 0);
    sizer_5->Add(negativeSlider, 1, wxEXPAND, 0);
    sizer_3->Add(sizer_5, 0, wxEXPAND, 0);
    sizer_6->Add(m_bmpSubstract, 0, wxALIGN_RIGHT, 0);
    sizer_6->Add(positiveSlider, 1, wxEXPAND, 0);
    sizer_3->Add(sizer_6, 0, wxEXPAND, 0);
    SetSizer(sizer_3);
    // end wxGlade
}

