// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Jul 01 11:35:34 2010

#include <wx/wx.h>
#include <wx/image.h>

#ifndef COREIMAGECONTRASTWIDGETUI_H
#define COREIMAGECONTRASTWIDGETUI_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#define wxID_NegativeSlider wxID( "wxID_NegativeSlider" )
#define wxID_PositiveSlider wxID( "wxID_PositiveSlider" )
#include "add.xpm"
#include "substract.xpm"
#define wxID_EnableSliders wxID("wxID_ImageContrast_EnableSliders")

// end wxGlade


class coreImageContrastWidgetUI: public wxScrolledWindow {
public:
    // begin wxGlade: coreImageContrastWidgetUI::ids
    // end wxGlade

    coreImageContrastWidgetUI(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    // begin wxGlade: coreImageContrastWidgetUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: coreImageContrastWidgetUI::attributes
    wxCheckBox* m_checkEnable;
    wxStaticBitmap* m_bmpAdd;
    wxSlider* negativeSlider;
    wxStaticBitmap* m_bmpSubstract;
    wxSlider* positiveSlider;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnChkBoxEnable(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnSliderNegativeContrast(wxScrollEvent &event); // wxGlade: <event_handler>
    virtual void OnSliderPositiveContrast(wxScrollEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // COREIMAGECONTRASTWIDGETUI_H
