// -*- C++ -*- generated by wxGlade 0.6.3 on Tue Apr 27 14:43:33 2010

#include <wx/wx.h>
#include <wx/image.h>

#ifndef CORESIMPLEPROCESSINGWIDGETUI_H
#define CORESIMPLEPROCESSINGWIDGETUI_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#define wxID_btnApply wxID( "wxID_btnApply" )

// end wxGlade


class GMWIDGETS_EXPORT coreSimpleProcessingWidgetUI: public wxPanel {
public:
    // begin wxGlade: coreSimpleProcessingWidgetUI::ids
    // end wxGlade

    coreSimpleProcessingWidgetUI(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    // begin wxGlade: coreSimpleProcessingWidgetUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: coreSimpleProcessingWidgetUI::attributes
    wxButton* m_btnApply;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnApply(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // CORESIMPLEPROCESSINGWIDGETUI_H
