// -*- C++ -*- generated by wxGlade 0.6.3 on Tue Apr 27 14:43:33 2010

#include "coreSimpleProcessingWidgetUI.h"

// begin wxGlade: ::extracode

// end wxGlade


coreSimpleProcessingWidgetUI::coreSimpleProcessingWidgetUI(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: coreSimpleProcessingWidgetUI::coreSimpleProcessingWidgetUI
    m_btnApply = new wxButton(this, wxID_btnApply, wxT("Apply"));

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(coreSimpleProcessingWidgetUI, wxPanel)
    // begin wxGlade: coreSimpleProcessingWidgetUI::event_table
    EVT_BUTTON(wxID_btnApply, coreSimpleProcessingWidgetUI::OnApply)
    // end wxGlade
END_EVENT_TABLE();


void coreSimpleProcessingWidgetUI::OnApply(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (coreSimpleProcessingWidgetUI::OnApply) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


// wxGlade: add coreSimpleProcessingWidgetUI event handlers


void coreSimpleProcessingWidgetUI::set_properties()
{
    // begin wxGlade: coreSimpleProcessingWidgetUI::set_properties
    // end wxGlade
}


void coreSimpleProcessingWidgetUI::do_layout()
{
    // begin wxGlade: coreSimpleProcessingWidgetUI::do_layout
    wxBoxSizer* GlobalSizer = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    sizer_1->Add(m_btnApply, 0, wxALL|wxALIGN_RIGHT, 5);
    GlobalSizer->Add(sizer_1, 1, wxEXPAND, 0);
    SetSizer(GlobalSizer);
    GlobalSizer->Fit(this);
    // end wxGlade
}

