// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Oct 10 10:20:18 2008

#include <wx/wx.h>
#include <wx/image.h>
#include "wxID.h"

#ifndef _SandboxPluginShapeScalePanelWidgetUI_H
#define _SandboxPluginShapeScalePanelWidgetUI_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade

//define id for widget controls
#define wxID_BTN_SCALE wxID("SandboxPluginShapeScalePanelWidgetUIBtnScale")

class SandboxPluginShapeScalePanelWidgetUI: public wxScrolledWindow {
public:
    // begin wxGlade: SandboxPluginShapeScalePanelWidgetUI::ids
    // end wxGlade

    SandboxPluginShapeScalePanelWidgetUI(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    // begin wxGlade: SandboxPluginShapeScalePanelWidgetUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: SandboxPluginShapeScalePanelWidgetUI::attributes
    wxStaticBox* m_GlobalVolumeClosing_staticbox;
    wxStaticText* m_labelScale;
    wxTextCtrl* m_textScale;
    wxButton* m_btnScale;
    // end wxGlade
}; // wxGlade: end class


#endif // _SandboxPluginShapeScalePanelWidgetUI_H
