// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Jan 21 15:10:58 2011

#include "corePreferencesDialogUI.h"

// begin wxGlade: ::extracode

// end wxGlade


corePreferencesDialogUI::corePreferencesDialogUI(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: corePreferencesDialogUI::corePreferencesDialogUI
    m_btnOK = new wxButton(this, wxID_OK, wxT("OK"));
    m_btnApply = new wxButton(this, wxID_APPLY, wxT("Apply"));
    m_btnCancel = new wxButton(this, wxID_CANCEL, wxT("Cancel"));

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(corePreferencesDialogUI, wxDialog)
    // begin wxGlade: corePreferencesDialogUI::event_table
    EVT_BUTTON(wxID_OK, corePreferencesDialogUI::OnOK)
    EVT_BUTTON(wxID_APPLY, corePreferencesDialogUI::OnOK)
    EVT_BUTTON(wxID_CANCEL, corePreferencesDialogUI::OnCancel)
    // end wxGlade
END_EVENT_TABLE();


void corePreferencesDialogUI::OnOK(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (corePreferencesDialogUI::OnOK) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void corePreferencesDialogUI::OnCancel(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (corePreferencesDialogUI::OnCancel) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


// wxGlade: add corePreferencesDialogUI event handlers


void corePreferencesDialogUI::set_properties()
{
    // begin wxGlade: corePreferencesDialogUI::set_properties
    SetTitle(wxT("GIMIAS User Registration"));
    SetSize(wxSize(500, 485));
    m_btnOK->SetDefault();
    m_btnApply->SetDefault();
    m_btnCancel->SetDefault();
    // end wxGlade
}


void corePreferencesDialogUI::do_layout()
{
    // begin wxGlade: corePreferencesDialogUI::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    sizer_2->Add(m_btnOK, 0, wxALL, 5);
    sizer_2->Add(m_btnApply, 0, wxALL, 5);
    sizer_2->Add(m_btnCancel, 0, wxALL, 5);
    sizer_1->Add(sizer_2, 0, wxALL|wxALIGN_RIGHT, 5);
    SetSizer(sizer_1);
    Layout();
    // end wxGlade
}

