// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Jan 21 15:10:58 2011

#include <wx/wx.h>
#include <wx/image.h>

#ifndef COREPREFERENCESDIALOGUI_H
#define COREPREFERENCESDIALOGUI_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#include "wxID.h"

#define wxID_BTN_REGISTER wxID( "wxID_BTN_REGISTER" )
#define wxID_BTN_REMIND_ME_LATER wxID( "wxID_BTN_REMIND_ME_LATER")
#define wxID_BTN_DO_NOT_ASK wxID( "wxID_BTN_DO_NOT_ASK")

// end wxGlade


class corePreferencesDialogUI: public wxDialog {
public:
    // begin wxGlade: corePreferencesDialogUI::ids
    // end wxGlade

    corePreferencesDialogUI(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: corePreferencesDialogUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: corePreferencesDialogUI::attributes
    wxButton* m_btnOK;
    wxButton* m_btnApply;
    wxButton* m_btnCancel;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnOK(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnCancel(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // COREPREFERENCESDIALOGUI_H
