// -*- C++ -*- generated by wxGlade 0.6.3 on Sat Jan 08 00:52:29 2011

#include <wx/wx.h>
#include <wx/image.h>

#ifndef TAVERNAPLUGINCONFIGURATIONPANELWIDGETUI_H
#define TAVERNAPLUGINCONFIGURATIONPANELWIDGETUI_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class TavernaPluginConfigurationPanelWidgetUI: public wxScrolledWindow {
public:
    // begin wxGlade: TavernaPluginConfigurationPanelWidgetUI::ids
    // end wxGlade

    TavernaPluginConfigurationPanelWidgetUI(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    // begin wxGlade: TavernaPluginConfigurationPanelWidgetUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: TavernaPluginConfigurationPanelWidgetUI::attributes
    wxStaticText* label_1;
    wxTextCtrl* m_txtTavernaPath;
    wxButton* button_1;
    wxStaticText* label_1_copy;
    wxTextCtrl* m_txtTavernaCaption;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnBrowse(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // TAVERNAPLUGINCONFIGURATIONPANELWIDGETUI_H
