// -*- C++ -*- generated by wxGlade 0.6.3 on Sat Jan 08 00:52:29 2011

#include "TavernaPluginConfigurationPanelWidgetUI.h"

// begin wxGlade: ::extracode

// end wxGlade


TavernaPluginConfigurationPanelWidgetUI::TavernaPluginConfigurationPanelWidgetUI(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxScrolledWindow(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: TavernaPluginConfigurationPanelWidgetUI::TavernaPluginConfigurationPanelWidgetUI
    label_1 = new wxStaticText(this, wxID_ANY, wxT("Taverna executable"));
    m_txtTavernaPath = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    button_1 = new wxButton(this, wxID_ANY, wxT("..."));
    label_1_copy = new wxStaticText(this, wxID_ANY, wxT("Taverna caption"));
    m_txtTavernaCaption = new wxTextCtrl(this, wxID_ANY, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(TavernaPluginConfigurationPanelWidgetUI, wxScrolledWindow)
    // begin wxGlade: TavernaPluginConfigurationPanelWidgetUI::event_table
    EVT_BUTTON(wxID_ANY, TavernaPluginConfigurationPanelWidgetUI::OnBrowse)
    // end wxGlade
END_EVENT_TABLE();


void TavernaPluginConfigurationPanelWidgetUI::OnBrowse(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (TavernaPluginConfigurationPanelWidgetUI::OnBrowse) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


// wxGlade: add TavernaPluginConfigurationPanelWidgetUI event handlers


void TavernaPluginConfigurationPanelWidgetUI::set_properties()
{
    // begin wxGlade: TavernaPluginConfigurationPanelWidgetUI::set_properties
    SetScrollRate(10, 10);
    button_1->SetMinSize(wxSize(20, 20));
    // end wxGlade
}


void TavernaPluginConfigurationPanelWidgetUI::do_layout()
{
    // begin wxGlade: TavernaPluginConfigurationPanelWidgetUI::do_layout
    wxBoxSizer* GlobalSizer = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_3_copy = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxHORIZONTAL);
    sizer_2->Add(label_1, 1, wxALIGN_CENTER_VERTICAL, 0);
    sizer_3->Add(m_txtTavernaPath, 1, wxEXPAND, 1);
    sizer_3->Add(button_1, 0, 0, 0);
    sizer_2->Add(sizer_3, 0, wxEXPAND, 0);
    sizer_2->Add(label_1_copy, 1, wxALIGN_CENTER_VERTICAL, 0);
    sizer_3_copy->Add(m_txtTavernaCaption, 1, wxEXPAND, 1);
    sizer_2->Add(sizer_3_copy, 0, wxEXPAND, 0);
    sizer_1->Add(sizer_2, 1, wxALL|wxEXPAND, 5);
    GlobalSizer->Add(sizer_1, 0, wxEXPAND, 5);
    SetSizer(GlobalSizer);
    GlobalSizer->Fit(this);
    // end wxGlade
}

