// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Jun 17 10:17:27 2010

#include "ManualSegmentationPanelWidgetUI.h"

// begin wxGlade: ::extracode

// end wxGlade


ManualSegmentationPanelWidgetUI::ManualSegmentationPanelWidgetUI(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxScrolledWindow(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: ManualSegmentationPanelWidgetUI::ManualSegmentationPanelWidgetUI
    sizer_4_staticbox = new wxStaticBox(this, -1, wxT("Select level"));
    sizer_1_staticbox = new wxStaticBox(this, -1, wxT("Lookup table"));
    sizer_2_staticbox = new wxStaticBox(this, -1, wxT("Add Level"));
    m_txtAdd = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    m_btnAdd = new wxButton(this, wxID_BTN_ADD , wxT("Add"));
    const wxString *m_ComboLevel_choices = NULL;
    m_ComboLevel = new wxComboBox(this, wxID_COMBO_LEVEL, wxT(""), wxDefaultPosition, wxDefaultSize, 0, m_ComboLevel_choices, wxCB_DROPDOWN | wxTE_PROCESS_ENTER);
	m_roiColorSelector = new mitk::wxMitkColorSelectorControl(this, wxID_COLOR_SELECTOR,wxColour(0,0,0),wxDefaultPosition,wxDefaultSize,!wxCLRP_USE_TEXTCTRL);
	m_chkEraseOnlySelectedColor = new wxCheckBox(this, wxID_CHK_COLOR, wxT("Erase only selected color"));
    const wxString *m_ComboLUT_choices = NULL;
    m_ComboLUT = new wxComboBox(this, wxID_COMBO_LUT , wxT(""), wxDefaultPosition, wxDefaultSize, 0, m_ComboLUT_choices, wxCB_DROPDOWN | wxCB_READONLY);
    m_btnEnableInteraction = new wxToggleButton(this, wxID_EnableInteraction, wxT("Disable Interaction"));

    set_properties();
    do_layout();
    // end wxGlade
}


void ManualSegmentationPanelWidgetUI::set_properties()
{
    // begin wxGlade: ManualSegmentationPanelWidgetUI::set_properties
    SetScrollRate(10, 10);
    m_btnEnableInteraction->SetValue(1);
    // end wxGlade
}


void ManualSegmentationPanelWidgetUI::do_layout()
{
    // begin wxGlade: ManualSegmentationPanelWidgetUI::do_layout
    wxBoxSizer* GlobalSizer = new wxBoxSizer(wxVERTICAL);
    wxStaticBoxSizer* sizer_1 = new wxStaticBoxSizer(sizer_1_staticbox, wxHORIZONTAL);
    wxStaticBoxSizer* sizer_4 = new wxStaticBoxSizer(sizer_4_staticbox, wxVERTICAL);
    wxBoxSizer* sizer_6 = new wxBoxSizer(wxHORIZONTAL);
    wxStaticBoxSizer* sizer_2 = new wxStaticBoxSizer(sizer_2_staticbox, wxVERTICAL);
    wxBoxSizer* sizer_5 = new wxBoxSizer(wxHORIZONTAL);
    sizer_5->Add(m_txtAdd, 1, 0, 0);
    sizer_5->Add(20, 20, 0, 0, 0);
    sizer_5->Add(m_btnAdd, 1, 0, 0);
    sizer_2->Add(sizer_5, 0, wxEXPAND, 0);
    GlobalSizer->Add(sizer_2, 0, wxEXPAND, 0);
    sizer_6->Add(m_ComboLevel, 1, wxEXPAND, 0);
    sizer_6->Add(20, 20, 0, 0, 0);
    sizer_6->Add(20, 20, 0, 0, 0);
    sizer_6->Add(m_roiColorSelector, 1, 0, 0);
    sizer_4->Add(sizer_6, 0, wxEXPAND, 0);
    sizer_4->Add(m_chkEraseOnlySelectedColor, 1, 0, 0);
    GlobalSizer->Add(sizer_4, 0, wxEXPAND, 0);
    sizer_1->Add(m_ComboLUT, 1, 0, 0);
    GlobalSizer->Add(sizer_1, 0, wxEXPAND, 0);
    GlobalSizer->Add(m_btnEnableInteraction, 0, wxALL|wxEXPAND, 0);
    SetSizer(GlobalSizer);
    GlobalSizer->Fit(this);
    // end wxGlade
}

