/*
* Copyright (c) 2009,
* Computational Image and Simulation Technologies in Biomedicine (CISTIB),
* Universitat Pompeu Fabra (UPF), Barcelona, Spain. All rights reserved.
* See license.txt file for details.
*/

// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Aug 07 17:20:03 2008

#include <wx/wx.h>
#include <wx/image.h>

#ifndef COREUSERHELPERWIDGETUI_H
#define COREUSERHELPERWIDGETUI_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade

#define MAX_SIZERS 3

/** 
\brief UserHelperWidget's UI
\ingroup gmWidgets
\author 
\sa Core::Widgets::UserHelper
*/
class coreUserHelperWidgetUI: public wxScrolledWindow {
public:
    // begin wxGlade: coreUserHelperWidgetUI::ids
    // end wxGlade

    coreUserHelperWidgetUI(
		wxWindow* parent, 
		int id, 
		const wxPoint& pos=wxDefaultPosition, 
		const wxSize& size=wxDefaultSize, 
		long style=0);

private:
    // begin wxGlade: coreUserHelperWidgetUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: coreUserHelperWidgetUI::attributes
    wxStaticBox* m_sizer_1_staticbox;
    // end wxGlade

	wxStaticBitmap* m_bitmap[ MAX_SIZERS ];
	wxStaticText* m_label[ MAX_SIZERS ];
	wxBoxSizer* m_sizer[ MAX_SIZERS ];

}; // wxGlade: end class


#endif // COREUSERHELPERWIDGETUI_H
