/*
* Copyright (c) 2009,
* Computational Image and Simulation Technologies in Biomedicine (CISTIB),
* Universitat Pompeu Fabra (UPF), Barcelona, Spain. All rights reserved.
* See license.txt file for details.
*/
// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Aug 07 17:20:03 2008

#include "coreUserHelperWidgetUI.h"

// begin wxGlade: ::extracode

// end wxGlade


coreUserHelperWidgetUI::coreUserHelperWidgetUI(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxScrolledWindow(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: coreUserHelperWidgetUI::coreUserHelperWidgetUI
    m_sizer_1_staticbox = new wxStaticBox(this, -1, wxT("User Information"));
    
	for ( int i = 0 ; i < MAX_SIZERS ; i++ )
	{
		m_bitmap[ i ] = new wxStaticBitmap();
		m_bitmap[ i ]->Create( this, wxID_ANY, wxNullBitmap );
		m_bitmap[ i ]->Show( false );
		m_label[ i ] = new wxStaticText(this, wxID_ANY, wxEmptyString);
	}

    set_properties();
    do_layout();
    // end wxGlade
}


void coreUserHelperWidgetUI::set_properties()
{
    // begin wxGlade: coreUserHelperWidgetUI::set_properties
    // end wxGlade
	this->SetScrollbars(0,10,0,10);
}


void coreUserHelperWidgetUI::do_layout()
{
    // begin wxGlade: coreUserHelperWidgetUI::do_layout
    wxStaticBoxSizer* m_sizer_1 = new wxStaticBoxSizer(m_sizer_1_staticbox, wxVERTICAL);

	for ( int i = 0 ; i < MAX_SIZERS ; i++ )
	{
	   m_sizer[ i ] = new wxBoxSizer(wxHORIZONTAL);
	   m_sizer[ i ]->Add(m_bitmap[ i ], 0, 0, 0);
	   m_sizer[ i ]->Add(m_label[ i ], 0, wxEXPAND, 0);
	   m_sizer_1->Add(m_sizer[ i ], 0, wxEXPAND, 0);
	}
    SetSizer(m_sizer_1);
    m_sizer_1->Fit(this);
    // end wxGlade
}

