// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Mar 06 11:33:45 2009

#include "coreFuraPopupWidgetUI.h"
#include "coreKernel.h"

// begin wxGlade: ::extracode

// end wxGlade

#define BITMAP_FOLDER Core::Runtime::Kernel::GetApplicationSettings()->GetApplicationPathSubPath("resource/fura2.jpg")

coreFuraPopupWidgetUI::coreFuraPopupWidgetUI(
	wxWindow* parent, 
	int id, 
	const wxString& title, 
	const wxPoint& pos,
	const wxSize& size, 
	long style,
	const wxString& name):
	wxDialog(parent, id, title, pos, size, style, name)
{
    // begin wxGlade: coreFuraPopupWidgetUI::coreFuraPopupWidgetUI
    bitmap_1 = new wxStaticBitmap(this, wxID_ANY, wxBitmap(wxString::FromAscii(BITMAP_FOLDER.c_str()), wxBITMAP_TYPE_ANY));
    label_Title = new wxStaticText(this, wxID_ANY, wxT("Enter Ansys Task Parameters:"));

	static_line_1 = new wxStaticLine(this, wxID_ANY);
    label_8 = new wxStaticText(this, wxID_ANY, wxEmptyString);
    static_line_2 = new wxStaticLine(this, wxID_ANY);
    label_ServerName = new wxStaticText(this, wxID_ANY, wxT("Server Name:   "));
    txtCtrl_ServerName = new wxTextCtrl(this, wxID_ANY, wxT("argo.upf.edu"));
    label_PortNumber = new wxStaticText(this, wxID_ANY, wxT("Port Number:    "));
    txtCtrl_Port_Number = new wxTextCtrl(this, wxID_ANY, wxT("8112"));
    label_DefinitionFile = new wxStaticText(this, wxID_ANY, wxT("Definition File:   "));

	// Read Only to avoid crashin the fura when the file is not selected through the browse window
	txtCtrl_DefinitionFile = new wxTextCtrl(this, wxID_ANY, wxEmptyString,wxDefaultPosition, wxDefaultSize, wxTE_READONLY);

    btn_Browse = new wxButton(this, wxID_ANY, wxT("Browse"));
    static_line_3 = new wxStaticLine(this, wxID_ANY);
    static_line_4 = new wxStaticLine(this, wxID_ANY);
    btn_OK = new wxButton(this, wxID_OK, wxEmptyString);
    btn_Cancel = new wxButton(this, wxID_CANCEL, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void coreFuraPopupWidgetUI::set_properties()
{
    // begin wxGlade: coreFuraPopupWidgetUI::set_properties
    bitmap_1->SetMinSize(wxSize(-1, -1));
    label_Title->SetMinSize(wxSize(250, 15));

	label_Title->SetFont(wxFont(10, wxMODERN, wxNORMAL, wxBOLD, 0, wxT("New Times Roman")));
    //txtCtrl_DefinitionFile->SetMinSize(wxSize(150, 20));
    btn_Browse->SetMinSize(wxSize(50, 20));
    // end wxGlade
}


void coreFuraPopupWidgetUI::do_layout()
{
    // begin wxGlade: coreFuraPopupWidgetUI::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_8 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_7 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_6 = new wxBoxSizer(wxHORIZONTAL);
    sizer_1->Add(bitmap_1, 0, 0, 0);
	sizer_1->Add(label_Title, 0, wxALL, 3);
    sizer_1->Add(static_line_1, 0, wxEXPAND, 0);
    sizer_1->Add(label_8, 0, 0, 0);
    sizer_1->Add(static_line_2, 0, wxEXPAND, 0);
    sizer_6->Add(label_ServerName, 0, wxALL, 3);
    sizer_6->Add(txtCtrl_ServerName, 1, wxEXPAND, 0);
    sizer_1->Add(sizer_6, 0, wxEXPAND, 0);
    sizer_7->Add(label_PortNumber, 0, wxALL, 3);
    sizer_7->Add(txtCtrl_Port_Number, 1, wxEXPAND, 0);
    sizer_1->Add(sizer_7, 0, wxEXPAND, 0);
    sizer_3->Add(label_DefinitionFile, 0, wxALL, 3);
    sizer_3->Add(txtCtrl_DefinitionFile, 1, wxALL, 0);
    sizer_3->Add(btn_Browse, 0, wxALL, 3);
    sizer_1->Add(sizer_3, 1, wxEXPAND, 0);
    sizer_1->Add(sizer_8, 1, wxEXPAND, 0);
    sizer_1->Add(static_line_3, 0, wxEXPAND, 0);
    sizer_1->Add(static_line_4, 0, wxEXPAND, 0);
    sizer_2->Add(btn_OK, 0, 0, 0);
    sizer_2->Add(btn_Cancel, 0, wxLEFT, 10);
    sizer_1->Add(sizer_2, 0, wxALL|wxALIGN_RIGHT, 5);
    SetSizer(sizer_1);
    //sizer_1->Fit(this);
    // end wxGlade
}

