// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Mar 06 11:33:45 2009

#include <wx/wx.h>
#include <wx/image.h>

#ifndef COREFURAPOPUPWIDGETUI_H
#define COREFURAPOPUPWIDGETUI_H

// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


/** 
\brief 
\ingroup gmWidgets
\author 
\date 
*/
class coreFuraPopupWidgetUI: public wxDialog {
public:
    // begin wxGlade: coreFuraPopupWidgetUI::ids
    // end wxGlade

	coreFuraPopupWidgetUI(
		wxWindow* parent, 
		wxWindowID id, 
		const wxString& title, 
		const wxPoint& pos = wxDefaultPosition, 
		const wxSize& size = wxDefaultSize, 
		long style = wxDEFAULT_DIALOG_STYLE, 
		const wxString& name = wxT("dialogBox"));

private:
    // begin wxGlade: coreFuraPopupWidgetUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: coreFuraPopupWidgetUI::attributes
    wxStaticBitmap* bitmap_1;
    wxStaticText* label_Title;
    wxStaticLine* static_line_1;
    wxStaticText* label_8;
    wxStaticLine* static_line_2;
    wxStaticText* label_ServerName;
    wxTextCtrl* txtCtrl_ServerName;
    wxStaticText* label_PortNumber;
    wxTextCtrl* txtCtrl_Port_Number;
    wxStaticText* label_DefinitionFile;
    wxTextCtrl* txtCtrl_DefinitionFile;
    wxButton* btn_Browse;
    wxStaticLine* static_line_3;
    wxStaticLine* static_line_4;
    wxButton* btn_OK;
    wxButton* btn_Cancel;
    wxStaticText* label_11_copy;
    // end wxGlade
}; // wxGlade: end class


#endif // COREFURAPOPUPWIDGETUI_H
