// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Aug 02 11:26:03 2010

#include <wx/wx.h>
#include <wx/image.h>

#ifndef WXMITKTRANSFORMVISUALPROPWIDGETUI_H
#define WXMITKTRANSFORMVISUALPROPWIDGETUI_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#include "wxID.h"

#define wxID_OFFSET_X wxID("wxID_OFFSET_X")
#define wxID_OFFSET_Y wxID("wxID_OFFSET_Y")
#define wxID_OFFSET_Z wxID("wxID_OFFSET_Z")

#define wxID_SPACING_X wxID("wxID_SPACING_X")
#define wxID_SPACING_Y wxID("wxID_SPACING_Y")
#define wxID_SPACING_Z wxID("wxID_SPACING_Z")

// end wxGlade


class wxMitkTransformVisualPropWidgetUI: public wxPanel {
public:
    // begin wxGlade: wxMitkTransformVisualPropWidgetUI::ids
    // end wxGlade

    wxMitkTransformVisualPropWidgetUI(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    // begin wxGlade: wxMitkTransformVisualPropWidgetUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: wxMitkTransformVisualPropWidgetUI::attributes
    wxStaticBox* Offset_staticbox;
    wxStaticBox* Spacing_staticbox;
    wxStaticText* label_1;
    wxTextCtrl* m_txtSpacingX;
    wxStaticText* label_1_copy;
    wxTextCtrl* m_txtSpacingY;
    wxStaticText* label_1_copy_copy;
    wxTextCtrl* m_txtSpacingZ;
    wxStaticText* label_1_copy_1;
    wxTextCtrl* m_txtOffsetX;
    wxStaticText* label_1_copy_copy_1;
    wxTextCtrl* m_txtOffsetY;
    wxStaticText* label_1_copy_copy_copy;
    wxTextCtrl* m_txtOffsetZ;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnSpacingX(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnSpacingY(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnSpacingZ(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnOffsetX(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnOffsetY(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnOffsetZ(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // WXMITKTRANSFORMVISUALPROPWIDGETUI_H
