// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Sep 16 14:14:31 2010

#include "coreSurfaceSelectorWidgetUI.h"

// begin wxGlade: ::extracode

// end wxGlade


coreSurfaceSelectorWidgetUI::coreSurfaceSelectorWidgetUI(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxScrolledWindow(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: coreSurfaceSelectorWidgetUI::coreSurfaceSelectorWidgetUI
    sizer_2_staticbox = new wxStaticBox(this, -1, wxT("Select Tools"));
    sizer_6_staticbox = new wxStaticBox(this, -1, wxT("Interactor Type"));
    checkbox_1 = new wxCheckBox(this, wxID_SELECTCHKBOX, wxT("Select"));
    checkbox_2 = new wxCheckBox(this, wxID_UNSELECTCHKBOX, wxT("Unselect"));
    radio_btn_1 = new wxRadioButton(this, wxID_TRIANGLE, wxT("TriangleSelect"));
    label_1 = new wxStaticText(this, wxID_ANY, wxEmptyString);
    radio_btn_2 = new wxRadioButton(this, wxID_SPHERE, wxT("SphereSelect"));
    label_2 = new wxStaticText(this, wxID_ANY, wxEmptyString);
    radio_btn_3 = new wxRadioButton(this, wxID_BRUSH, wxT("BrushSelect"));
    label_3 = new wxStaticText(this, wxID_ANY, wxT("brush size"));
    spin_ctrl_1 = new wxSpinCtrl(this, wxID_SIZESPINCTRL, wxT("5"), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 1, 50);
    m_btnEnableSelection = new wxToggleButton(this, wxID_EnableSelection, wxT("Enable Selection"));
    m_removeCellsCkbox = new wxCheckBox(this, wxID_REMOVE_CELLS, wxT("Remove Cells"));
    m_LocalRefinerCkbox = new wxCheckBox(this, wxID_LOCAL_REFINER, wxT("Local Refiner"));
    //m_LoopSubdivisionCkbox = new wxCheckBox(this, wxID_LOOP_SUBDIV, wxT("Loop Subdivision"));
    m_TaubinSmoothCkbox = new wxCheckBox(this, wxID_TAUBIN_SMOOTH, wxT("Taubin Smooth"));
    //m_EdgeSwapCkbox = new wxCheckBox(this, wxID_EDGE_SWAP, wxT("Edge Swap"));

    set_properties();
    do_layout();
    // end wxGlade
}


// wxGlade: add coreSurfaceSelectorWidgetUI event handlers


void coreSurfaceSelectorWidgetUI::set_properties()
{
    // begin wxGlade: coreSurfaceSelectorWidgetUI::set_properties
    SetScrollRate(10, 10);
    checkbox_1->SetValue(1);
    radio_btn_1->SetValue(1);
    // end wxGlade
}


void coreSurfaceSelectorWidgetUI::do_layout()
{
    // begin wxGlade: coreSurfaceSelectorWidgetUI::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxVERTICAL);
    wxStaticBoxSizer* sizer_2 = new wxStaticBoxSizer(sizer_2_staticbox, wxVERTICAL);
    wxStaticBoxSizer* sizer_6 = new wxStaticBoxSizer(sizer_6_staticbox, wxHORIZONTAL);
    wxGridSizer* grid_sizer_1 = new wxGridSizer(3, 2, 0, 0);
    wxBoxSizer* sizer_8 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_9 = new wxBoxSizer(wxHORIZONTAL);
    sizer_3->Add(20, 8, 0, wxEXPAND, 0);
    sizer_9->Add(checkbox_1, 1, wxEXPAND, 0);
    sizer_9->Add(checkbox_2, 1, wxEXPAND, 0);
    sizer_3->Add(sizer_9, 0, wxEXPAND, 0);
    sizer_3->Add(20, 8, 0, wxEXPAND, 0);
    grid_sizer_1->Add(radio_btn_1, 0, 0, 0);
    grid_sizer_1->Add(label_1, 0, 0, 0);
    grid_sizer_1->Add(radio_btn_2, 0, 0, 0);
    grid_sizer_1->Add(label_2, 0, 0, 0);
    grid_sizer_1->Add(radio_btn_3, 0, 0, 0);
    sizer_8->Add(label_3, 0, 0, 0);
    sizer_8->Add(spin_ctrl_1, 0, 0, 0);
    grid_sizer_1->Add(sizer_8, 0, wxEXPAND, 0);
    sizer_6->Add(grid_sizer_1, 1, wxEXPAND, 0);
    sizer_3->Add(sizer_6, 1, wxALL|wxEXPAND, 5);
    sizer_3->Add(20, 8, 0, wxEXPAND, 0);
    sizer_3->Add(m_btnEnableSelection, 0, wxALL|wxEXPAND, 0);
    sizer_3->Add(20, 8, 0, wxEXPAND, 0);
    sizer_2->Add(m_removeCellsCkbox, 0, 0, 0);
    sizer_2->Add(m_LocalRefinerCkbox, 0, 0, 0);
  //  sizer_2->Add(m_LoopSubdivisionCkbox, 0, 0, 0);
    sizer_2->Add(m_TaubinSmoothCkbox, 0, 0, 0);
//    sizer_2->Add(m_EdgeSwapCkbox, 0, 0, 0);
    sizer_3->Add(sizer_2, 1, wxEXPAND, 0);
    sizer_1->Add(sizer_3, 0, wxEXPAND, 0);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    // end wxGlade
}

