// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Sep 16 14:14:31 2010

#include <wx/wx.h>
#include <wx/image.h>

#ifndef CORESURFACESELECTORWIDGETUI_H
#define CORESURFACESELECTORWIDGETUI_H

// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
#include <wx/tglbtn.h>
// end wxGlade

// begin wxGlade: ::extracode
#define wxID_RADIO_BOX_INTERACTOR_TYPE_SURFACE wxID("SelectSurfaceInteractorType")
#define wxID_EDGE_SWAP wxID("EdgeSwap")
#define wxID_REMOVE_CELLS wxID("RemoveCells")
#define wxID_LOCAL_REFINER wxID("LocalRefiner")
#define wxID_EnableSelection wxID("wxID_EnableSelection")
#define wxID_TAUBIN_SMOOTH wxID("TaubinSmooth")
#define wxID_LOOP_SUBDIV wxID("LoopSubdivision")
#define wxID_SELECTCHKBOX wxID("Selectcheckbox")
#define wxID_UNSELECTCHKBOX wxID("Unselectcheckbox")
#define wxID_TRIANGLE wxID("Triangle")
#define wxID_SPHERE wxID("Sphere")
#define wxID_BRUSH wxID("Brush")
#define wxID_SIZESPINCTRL wxID("BrushSize")


// end wxGlade


class coreSurfaceSelectorWidgetUI: public wxScrolledWindow {
public:
    // begin wxGlade: coreSurfaceSelectorWidgetUI::ids
    // end wxGlade

    coreSurfaceSelectorWidgetUI(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    // begin wxGlade: coreSurfaceSelectorWidgetUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: coreSurfaceSelectorWidgetUI::attributes
    wxStaticBox* sizer_2_staticbox;
    wxStaticBox* sizer_6_staticbox;
    wxCheckBox* checkbox_1;
    wxCheckBox* checkbox_2;
    wxRadioButton* radio_btn_1;
    wxStaticText* label_1;
    wxRadioButton* radio_btn_2;
    wxStaticText* label_2;
    wxRadioButton* radio_btn_3;
    wxStaticText* label_3;
    wxSpinCtrl* spin_ctrl_1;
    wxToggleButton* m_btnEnableSelection;
    wxCheckBox* m_removeCellsCkbox;
    wxCheckBox* m_LocalRefinerCkbox;
    wxCheckBox* m_LoopSubdivisionCkbox;
    wxCheckBox* m_TaubinSmoothCkbox;
    wxCheckBox* m_EdgeSwapCkbox;
    // end wxGlade

}; // wxGlade: end class


#endif // CORESURFACESELECTORWIDGETUI_H
