// -*- C++ -*- generated by wxGlade 0.6.3 on Wed Sep 02 10:30:41 2009

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/grid.h>
// end wxGlade

#include "coreDataEntity.h"


#ifndef CORENUMERICDATAWIDGET_H
#define CORENUMERICDATAWIDGET_H


// begin wxGlade: ::extracode
// end wxGlade

namespace Core{
namespace Widgets{

class GMWIDGETS_EXPORT NumericDataWidget: public wxPanel {
public:
    // begin wxGlade: NumericDataWidget::ids
    // end wxGlade

    NumericDataWidget(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

	//! Updates the state of the widget
	void UpdateWidget(std::vector<blTagMap::Pointer>  tagMapVector, int timeStep = 1);

	//!
	//wxString FormatValueToString(boost::any& anyValue);

private:
    // begin wxGlade: NumericDataWidget::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: NumericDataWidget::attributes
    wxGrid* gridNumericResults;
    // end wxGlade

private:
}; // wxGlade: end class

} // namespce Widgets
} // namespace Core

#endif // CORENUMERICDATAWIDGET_H
