// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Jan 21 00:12:56 2011

#include "TavernaPluginWorkingAreaUI.h"

// begin wxGlade: ::extracode

// end wxGlade


TavernaPluginWorkingAreaUI::TavernaPluginWorkingAreaUI(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxScrolledWindow(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: TavernaPluginWorkingAreaUI::TavernaPluginWorkingAreaUI
    m_lblEmpty = new wxStaticText(this, wxID_ANY, wxT("Please configure Taverna Workbench \nin the Preferences dialog"), wxDefaultPosition, wxDefaultSize, wxALIGN_CENTRE);

    set_properties();
    do_layout();
    // end wxGlade
}


void TavernaPluginWorkingAreaUI::set_properties()
{
    // begin wxGlade: TavernaPluginWorkingAreaUI::set_properties
    SetScrollRate(10, 10);
    m_lblEmpty->SetFont(wxFont(16, wxDEFAULT, wxNORMAL, wxNORMAL, 0, wxT("")));
    // end wxGlade
}


void TavernaPluginWorkingAreaUI::do_layout()
{
    // begin wxGlade: TavernaPluginWorkingAreaUI::do_layout
    wxBoxSizer* GlobalSizer = new wxBoxSizer(wxVERTICAL);
    GlobalSizer->Add(m_lblEmpty, 1, wxALL|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 5);
    SetSizer(GlobalSizer);
    GlobalSizer->Fit(this);
    // end wxGlade
}

