// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Jun 14 16:50:51 2010

#include "CGNSFileWriterDialogUI.h"

// begin wxGlade: ::extracode

// end wxGlade


CGNSFileWriterDialogUI::CGNSFileWriterDialogUI(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxTHICK_FRAME)
{
    // begin wxGlade: CGNSFileWriterDialogUI::CGNSFileWriterDialogUI
    sizer_3_staticbox = new wxStaticBox(this, -1, wxT("Vectors"));
    sizer_2_staticbox = new wxStaticBox(this, -1, wxT("Scalars"));
    label_1 = new wxStaticText(this, wxID_ANY, wxT("   Please provide the fields you want to write.   "));
    m_btnOk = new wxButton(this, wxID_OK, wxT("Ok"));

    set_properties();
    do_layout();
    // end wxGlade
}


void CGNSFileWriterDialogUI::set_properties()
{
    // begin wxGlade: CGNSFileWriterDialogUI::set_properties
    SetTitle(wxT("CGNS file writer"));
    // end wxGlade
}


void CGNSFileWriterDialogUI::do_layout()
{
    // begin wxGlade: CGNSFileWriterDialogUI::do_layout
    sizer_1 = new wxBoxSizer(wxVERTICAL);
    sizer_3 = new wxStaticBoxSizer(sizer_3_staticbox, wxVERTICAL);
    sizer_2 = new wxStaticBoxSizer(sizer_2_staticbox, wxVERTICAL);
    sizer_1->Add(20, 20, 0, 0, 0);
    sizer_1->Add(label_1, 0, wxALL|wxALIGN_CENTER_HORIZONTAL, 0);
    sizer_1->Add(20, 20, 0, 0, 0);
    sizer_1->Add(sizer_2, 1, wxEXPAND|wxALIGN_CENTER_HORIZONTAL, 0);
    sizer_1->Add(20, 20, 0, 0, 0);
    sizer_1->Add(sizer_3, 1, wxEXPAND, 0);
    sizer_1->Add(20, 20, 0, 0, 0);
    sizer_1->Add(m_btnOk, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    Layout();
    // end wxGlade
}

