// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Jun 14 16:50:51 2010

#include <wx/wx.h>
#include <wx/image.h>

#ifndef CGNSFILEWRITERDIALOGUI_H
#define CGNSFILEWRITERDIALOGUI_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class CGNSFileWriterDialogUI: public wxDialog {
public:
    // begin wxGlade: CGNSFileWriterDialogUI::ids
    // end wxGlade

    CGNSFileWriterDialogUI(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: CGNSFileWriterDialogUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: CGNSFileWriterDialogUI::attributes
    wxStaticBox* sizer_3_staticbox;
    wxStaticBox* sizer_2_staticbox;
    wxStaticText* label_1;
    wxButton* m_btnOk;
	wxBoxSizer* sizer_1;
	wxStaticBoxSizer* sizer_3;
	wxStaticBoxSizer* sizer_2;
    // end wxGlade
}; // wxGlade: end class


#endif // CGNSFILEWRITERDIALOGUI_H
