// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Oct 24 09:55:28 2008

#include <wx/wx.h>
#include <wx/image.h>
#include "wxID.h"

#ifndef _SandboxPluginResamplePanelWidgetUI_H
#define _SandboxPluginResamplePanelWidgetUI_H

// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade

//define id for widget controls
#define wxID_BTN_Resample wxID("SandboxPluginResamplePanelWidgetUIBtnSub")
#define wxID_RESAMPLE_SPINX wxID("wxID_RESAMPLE_SPINX")
#define wxID_RESAMPLE_SPINY wxID("wxID_RESAMPLE_SPINY")
#define wxID_RESAMPLE_SPINZ wxID("wxID_RESAMPLE_SPINZ")


class SandboxPluginResamplePanelWidgetUI: public wxScrolledWindow {
public:
    // begin wxGlade: SandboxPluginResamplePanelWidgetUI::ids
    // end wxGlade

    SandboxPluginResamplePanelWidgetUI(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    // begin wxGlade: SandboxPluginResamplePanelWidgetUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: SandboxPluginResamplePanelWidgetUI::attributes
    wxButton* m_btnResample;
    wxStaticText* m_labelScale;
    wxSpinCtrl* m_SpinCtrlX;
    wxSpinCtrl* m_SpinCtrlY;
    wxSpinCtrl* m_SpinCtrlZ;
    // end wxGlade
}; // wxGlade: end class


#endif // _SandboxPluginResamplePanelWidgetUI_H
