/*
* Copyright (c) 2009,
* Computational Image and Simulation Technologies in Biomedicine (CISTIB),
* Universitat Pompeu Fabra (UPF), Barcelona, Spain. All rights reserved.
* See license.txt file for details.
*/

#ifndef _SandboxPluginResamplePanelWidget_H
#define _SandboxPluginResamplePanelWidget_H

#include "SandboxPluginResampleProcessor.h"
#include "SandboxPluginResamplePanelWidgetUI.h"
#include "coreProcessingWidget.h"

// CoreLib
#include "coreProcessorOutputObserver.h"

namespace Core{ namespace Widgets {
	class UserHelper;
	class DataEntityListBrowser;
}}

namespace SandboxPlugin{

/**
PanelWidget for interacting with SandboxPlugin::ResampleProcessor.

The parent class SandboxPluginResamplePanelWidgetUI contains all the code for 
buttons, labels, layouts, etc.

The ResamplePanelWidget provides the functions that handle the GUI events 
generated by SandboxPluginResamplePanelWidgetUI (see for example the function 
OnBtnSub).

SandboxPluginResamplePanelWidgetUI is created with wxGlade, a graphical 
GUI editor. It is encouraged to use wxGlade for designing your widgets.

\note In Gimias there's several PanelWidgets for different processors in 
different plug-ins. All the panel widgets are disabled except the active one that will be 
enabled ( Enable() ). The active one is the one that the user clicked.
If you need to catch the event when this panel widget is enabled or disabled
overwrite the function Enable( ). Be careful when you call Enable( true ) to 
this widget because the behavior will be unpredicted.

\ingroup SandboxPlugin
\author Berta Marti
\date 24 oct 2008
*/
class ResamplePanelWidget : 
	public SandboxPluginResamplePanelWidgetUI,
	public Core::Widgets::ProcessingWidget 
{

// OPERATIONS
public:
	//!
	coreDefineBaseWindowFactory( ResamplePanelWidget )

	//!
	ResamplePanelWidget( wxWindow* parent, int id = wxID_ANY, const wxPoint&  pos = wxDefaultPosition, const wxSize&  size = wxDefaultSize, long style = 0);

	//!
	~ResamplePanelWidget( );

	//! Add button events to the bridge and call UpdateWidget()
	void OnInit(  );
	
	//!
	bool Enable( bool enable /*= true */ );

	//! Update GUI from working data
	void UpdateWidget();

	//! Update working data from GUI
	void UpdateData();

	//!
	Core::BaseProcessor::Pointer GetProcessor( );

private:
	DECLARE_EVENT_TABLE()

	//! Validate GUI data
	bool Validate();

	//! Button has been pressed
	void OnBtnApply(wxCommandEvent& event);

	//!
	void UpdateHelperWidget( );

	//!
	void OnModifiedInput( int num );
	
	//!
	bool CheckInputPointSelected( );

// ATTRIBUTES
private:
	//! Working data of the processor
	ResampleProcessor::Pointer m_Processor;

};

} //namespace SandboxPlugin{

#endif //_SandboxPluginResamplePanelWidget_H
