// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Oct 24 09:55:28 2008

#include "SandboxPluginResamplePanelWidgetUI.h"

// begin wxGlade: ::extracode

// end wxGlade


SandboxPluginResamplePanelWidgetUI::SandboxPluginResamplePanelWidgetUI(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxScrolledWindow(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: SandboxPluginResamplePanelWidgetUI::SandboxPluginResamplePanelWidgetUI
    m_btnResample = new wxButton(this, wxID_BTN_Resample, wxT("Apply"));
    m_labelScale = new wxStaticText(this, wxID_ANY, wxT("Scale (0%-100%)"));
    m_SpinCtrlX = new wxSpinCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 100);
    m_SpinCtrlY = new wxSpinCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 100);
    m_SpinCtrlZ = new wxSpinCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 100);

    set_properties();
    do_layout();
    // end wxGlade
}


void SandboxPluginResamplePanelWidgetUI::set_properties()
{
    // begin wxGlade: SandboxPluginResamplePanelWidgetUI::set_properties
    SetScrollRate(10, 10);
    m_SpinCtrlX->SetMinSize(wxSize(50, 21));
    m_SpinCtrlY->SetMinSize(wxSize(50, 21));
    m_SpinCtrlZ->SetMinSize(wxSize(50, 21));
    // end wxGlade
}


void SandboxPluginResamplePanelWidgetUI::do_layout()
{
    // begin wxGlade: SandboxPluginResamplePanelWidgetUI::do_layout
    wxBoxSizer* GlobalSizer = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxHORIZONTAL);
    sizer_1->Add(m_btnResample, 0, wxALL|wxEXPAND, 5);
    sizer_3->Add(m_labelScale, 1, wxALIGN_CENTER_VERTICAL, 0);
    sizer_3->Add(m_SpinCtrlX, 0, 0, 0);
    sizer_3->Add(m_SpinCtrlY, 0, 0, 0);
    sizer_3->Add(m_SpinCtrlZ, 0, 0, 0);
    sizer_1->Add(sizer_3, 0, wxALL|wxEXPAND, 5);
    GlobalSizer->Add(sizer_1, 0, wxEXPAND, 5);
    SetSizer(GlobalSizer);
    GlobalSizer->Fit(this);
    // end wxGlade
}

