// Copyright 2009 Pompeu Fabra University (Computational Imaging Laboratory), Barcelona, Spain. Web: www.cilab.upf.edu.
// This software is distributed WITHOUT ANY WARRANTY; 
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Jan 14 17:39:16 2010

#include <wx/wx.h>
#include <wx/image.h>

#ifndef _ptExtractScalarWidget_H
#define _ptExtractScalarWidget_H

#include "corePluginMacros.h"
#include "coreProcessingWidget.h"
#include "coreExtractScalarProcessor.h"
#include "wxID.h"

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#define wx_IDptExtractScalarWidgetBtnEnable wxID( "wx_IDptExtractScalarWidgetBtnEnable" )
#define wx_IDExtractScalarTxtScalarName wxID( "wx_IDExtractScalarTxtScalarName" )
// end wxGlade


namespace Core{
namespace Widgets{

class LandmarkSelectorWidget;
}
}

/**
\brief Extract a list of scalar values from a mesh for a concrete point
\ingroup MeshEditorPlugin
\author Xavi Planes
\date 14 Jan 2010
*/
class PLUGIN_EXPORT ptExtractScalarWidget: 
	public wxPanel, 
	public Core::Widgets::ProcessingWidget {
public:
    // begin wxGlade: ptExtractScalarWidget::ids
    // end wxGlade

	coreDefineBaseWindowFactory( ptExtractScalarWidget )

    ptExtractScalarWidget(wxWindow* parent, int id = wxID_ANY, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

	//!
	~ptExtractScalarWidget( );

	//!
	Core::BaseProcessor::Pointer GetProcessor();

	//!
	bool Enable( bool enable = true );

private:
    // begin wxGlade: ptExtractScalarWidget::methods
    void set_properties();
    void do_layout();
    // end wxGlade

	//!
	virtual void OnButtonEnable(wxCommandEvent &event); // wxGlade: <event_handler>

	virtual void OnEnterText(wxCommandEvent &event); // wxGlade: <event_handler>

	//!
	void OnSelectedPoint();
	//!
	void OnSelectedInput();

	//!
	void ConnectInteractor();

	//!
	void DisconnectInteractor();

	//!
	void OnInit();

	//!
	void UpdateWidget();

	//!
	void UpdateData();


	DECLARE_EVENT_TABLE();

protected:
    // begin wxGlade: ptExtractScalarWidget::attributes
    wxToggleButton* m_btnEnable;
	wxStaticText* label_1;
	wxTextCtrl* m_txtScalarName;
    // end wxGlade

	//!
	Core::ExtractScalarProcessor::Pointer m_Processor;

}; // wxGlade: end class

#endif // ptExtractScalarWidget_H
