// -*- C++ -*- generated by wxGlade 0.6.3 on Wed May 05 14:46:25 2010

#include "ptMeshCreationWidget.h"

// begin wxGlade: ::extracode

// end wxGlade


ptMeshCreationWidget::ptMeshCreationWidget(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: ptMeshCreationWidget::ptMeshCreationWidget
    m_lblMethod = new wxStaticText(this, wxID_ANY, wxT("Method"));
    const wxString m_cmbMethod_choices[] = {
        wxT("Delaunay"),
        wxT("MarchingCubes")
    };
    m_cmbMethod = new wxComboBox(this, wxID_CMB_METHOD, wxT(""), wxDefaultPosition, wxDefaultSize, 2, m_cmbMethod_choices, wxCB_DROPDOWN);
    m_btnApply = new wxButton(this, wxID_BTN_APPLY, wxT("Apply"));

    set_properties();
    do_layout();
    // end wxGlade

	m_Processor = Core::MeshCreationProcessor::New( );
}


BEGIN_EVENT_TABLE(ptMeshCreationWidget, wxPanel)
    // begin wxGlade: ptMeshCreationWidget::event_table
    EVT_BUTTON(wxID_BTN_APPLY, ptMeshCreationWidget::OnApply)
    // end wxGlade
END_EVENT_TABLE();


void ptMeshCreationWidget::OnApply(wxCommandEvent &event)
{
    event.Skip();

	switch ( m_cmbMethod->GetSelection( ) )
	{
	case 0:
		m_Processor->SetDelaunayType( true );
		m_Processor->SetMarchingCubesType( false );
		break;
	case 1:
		m_Processor->SetDelaunayType( false );
		m_Processor->SetMarchingCubesType( true );
		break;
	}

	UpdateProcessor( );
}


// wxGlade: add ptMeshCreationWidget event handlers


void ptMeshCreationWidget::set_properties()
{
    // begin wxGlade: ptMeshCreationWidget::set_properties
    // end wxGlade
}


void ptMeshCreationWidget::do_layout()
{
	// begin wxGlade: ptMeshCreationWidget::do_layout
	wxBoxSizer* GlobalSizer = new wxBoxSizer(wxVERTICAL);
	wxBoxSizer* sizer_5_copy_2_copy_copy_1_copy_copy = new wxBoxSizer(wxHORIZONTAL);
	sizer_5_copy_2_copy_copy_1_copy_copy->Add(m_lblMethod, 1, 0, 0);
	sizer_5_copy_2_copy_copy_1_copy_copy->Add(m_cmbMethod, 0, 0, 0);
	GlobalSizer->Add(sizer_5_copy_2_copy_copy_1_copy_copy, 0, wxALL|wxEXPAND, 2);
	GlobalSizer->Add(m_btnApply, 0, wxALL|wxALIGN_RIGHT, 2);
	SetSizer(GlobalSizer);
	GlobalSizer->Fit(this);
	// end wxGlade
}

Core::BaseProcessor::Pointer ptMeshCreationWidget::GetProcessor()
{
	return m_Processor.GetPointer();
}

