// -*- C++ -*- generated by wxGlade 0.6.3 on Wed May 05 14:46:25 2010

#include <wx/wx.h>
#include <wx/image.h>

#ifndef MESHCREATIONWIDGET_H
#define MESHCREATIONWIDGET_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#define wxID_CMB_METHOD wxID( "wxID_CMB_METHOD" )
#define wxID_BTN_APPLY wxID( "wxID_BTN_APPLY" )


// end wxGlade

#define wxID_ptMeshCreationWidget wxID( "wxID_ptMeshCreationWidget" )

#include "coreProcessingWidget.h"
#include "coreMeshCreationProcessor.h"

class ptMeshCreationWidget: 
	public wxPanel,
	public Core::Widgets::ProcessingWidget {
public:
    // begin wxGlade: ptMeshCreationWidget::ids
    // end wxGlade

	coreDefineBaseWindowFactory( ptMeshCreationWidget )

    ptMeshCreationWidget(wxWindow* parent, int id = wxID_ptMeshCreationWidget, 
		const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

	//!
	Core::BaseProcessor::Pointer GetProcessor( );

private:
    // begin wxGlade: ptMeshCreationWidget::methods
    void set_properties();
    void do_layout();
    // end wxGlade

	virtual void OnApply(wxCommandEvent &event); // wxGlade: <event_handler>

protected:
    // begin wxGlade: ptMeshCreationWidget::attributes
	wxStaticText* m_lblMethod;
	wxComboBox* m_cmbMethod;
	wxButton* m_btnApply;
    // end wxGlade

    DECLARE_EVENT_TABLE();

	Core::MeshCreationProcessor::Pointer m_Processor;

}; // wxGlade: end class


#endif // MESHCREATIONWIDGET_H
