// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Dec 20 11:54:29 2010

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DICOMWORKINGAREAPANELWIDGETUI_H
#define DICOMWORKINGAREAPANELWIDGETUI_H

// begin wxGlade: ::dependencies
#include <wx/treectrl.h>
// end wxGlade

// begin wxGlade: ::extracode
#include "DicomImageViewWindow.h"
#include "wxMitkLevelWindowWidget.h"
#include "wxID.h"
#include "DicomTree.h"

#define wxID_DICOM_ADD_TO_DATALIST wxID("DicomAddToDataList")
#define wxID_DICOM_TREE wxID("DicomTree")
#define wxID_DICOM_IMG_TIME_SLIDER wxID("DicomImgTimeSlider")
#define wxID_DICOM_IMG_SPACE_SLIDER wxID("DicomImgStackSlider")
#define wxID_DICOM_COMBINE_DATA wxID("DicomCombineData")
#define wxID_DICOM_REORIENT_DATA wxID("DicomReorientData")
#define wxID_DICOM_EXPORT_RAW_DATA wxID("wxID_DICOM_EXPORT_RAW_DATA")
#define wxID_DICOM_TAGGED_MR wxID("wxID_DICOM_TAGGED_MR")
#define wxID_DICOM_TIME_TAG wxID("wxID_DICOM_TIME_TAG")
// end wxGlade


class DicomWorkingAreaPanelWidgetUI: public wxPanel {
public:
    // begin wxGlade: DicomWorkingAreaPanelWidgetUI::ids
    // end wxGlade

    DicomWorkingAreaPanelWidgetUI(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    // begin wxGlade: DicomWorkingAreaPanelWidgetUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DicomWorkingAreaPanelWidgetUI::attributes
    wxStaticBox* sizer_1_staticbox;
    wxStaticBox* sizer_11_staticbox;
    wxStaticBox* sizer_6_staticbox;
    DicomPlugin::DICOMTree* m_treeDicomView;
    wxStaticText* label_2;
    wxSlider* m_dcmSpaceSlider;
    wxStaticText* m_sliceName;
    DicomPlugin::DcmImageViewWindow* m_RenderWindow;
    wxStaticText* label_1;
    wxSlider* m_dcmTimeSlider;
    mitk::wxMitkLevelWindowWidget* m_LevelWindowWidget;
    wxCheckBox* m_chbCombineData;
    wxCheckBox* m_chbReorientData;
    wxCheckBox* m_chbExportRawData;
    wxCheckBox* m_chbTaggedMR;
    wxStaticText* label_3;
    wxComboBox* m_cmbTimeTag;
    wxButton* m_btnAddToDatalist;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnTimeTag(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // DICOMWORKINGAREAPANELWIDGETUI_H
