/*
* Copyright (c) 2009,
* Computational Image and Simulation Technologies in Biomedicine (CISTIB),
* Universitat Pompeu Fabra (UPF), Barcelona, Spain. All rights reserved.
* See license.txt file for details.
*/

#ifndef _MeshEditorPluginPCH_H
#define _MeshEditorPluginPCH_H

#include <wx/image.h>
#include <wx/wxprec.h>

#include "CILabNamespaceMacros.h"
#include "blMitkUnicode.h"
#include "blShapeUtils.h"
#include "boost/filesystem.hpp"
#include "coreDataEntityListBrowser.h"
#include "coreDataTreeHelper.h"
#include "coreProcessingWidget.h"
#include "coreLandmarkSelectorWidget.h"
#include "coreReportExceptionMacros.h"
#include "gblWxConnectorOfWidgetChangesToSlotFunction.h"
#include "gmWidgetsWin32Header.h"
#include "meVTKEdgeSwappingFilter.h"
#include "meVTKExtractMainSurfaceFilter.h"
#include "meVTKLocalRefinerFilter.h"
#include "meVTKLoopSubdivisionRefinerFilter.h"
#include "meVTKSkeletonizationFilter.h"
#include "meVTKSmoothFilter.h"
#include "meVTKVolumeClosingFilter.h"
#include "mitkProperties.h"
#include "wx/tglbtn.h"
#include "wx/xrc/xmlres.h"
#include "wxID.h"
#include "wxMitkScalarsArrayControl.h"
#include <blMitkUnicode.h>

#include "blShapeUtils.h"
#include "blSignalWriter.h"
#include "blVTKHelperTools.h"
#include "coreBaseFilter.h"
#include "coreBaseProcessor.h"
#include "coreDataContainer.h"
#include "coreDataEntity.h"
#include "coreDataEntityHelper.h"
#include "coreDataEntityHelper.txx"
#include "coreDataEntityHolder.h"
#include "coreDataEntityList.h"
#include "coreDataEntityUtilities.h"
#include "coreDirectory.h"
#include "coreImageDataEntityMacros.h"
#include "coreLoggerHelper.h"
#include "corePluginMacros.h"
#include "coreReportExceptionMacros.h"
#include "coreSmartPointerMacros.h"
#include "coreVTKImageDataHolder.h"
#include "coreVTKPolyDataHolder.h"
#include "itkCastImageFilter.h"
#include "itkCenteredEuler3DTransform.h"
#include "itkFlipImageFilter.h"
#include "itkGDCMImageIO.h"
#include "itkImageFileWriter.h"
#include "itkImageMaskSpatialObject.h"
#include "itkImageRegionIteratorWithIndex.h"
#include "itkImageSeriesReader.h"
#include "itkInvertIntensityImageFilter.h"
#include "itkNearestNeighborInterpolateImageFunction.h"
#include "itkNormalizeImageFilter.h"
#include "itkNumericSeriesFileNames.h"
#include "itkOtsuThresholdImageFilter.h"
#include "itkRayCastInterpolateImageFunction.h"
#include "itkResampleImageFilter.h"
#include "itkRescaleIntensityImageFilter.h"
#include "itkRigid3DTransform.h"
#include "itkSmartPointerForwardReference.txx"
#include "itkVTKImageIO.h"
#include "meMeshTypes.h"
#include "meNGOptimizeFilter.h"
#include "meNGTetraFilter.h"
#include "meRingCut.h"
#include "meVTKTetraGenerationFilter.h"
#include "meVTKVolumeClippingFilter.h"
#include "mitkImage.h"
#include "mitkImageDataItem.h"
#include "mitkImageWriter.h"
#include "vtkCleanPolyData.h"
#include "vtkDelaunay3D.h"
#include "vtkGeometryFilter.h"
#include "vtkImageData.h"
#include "vtkImageGaussianSmooth.h"
#include "vtkImageReslice.h"
#include "vtkMarchingCubes.h"
#include "vtkPointData.h"
#include "vtkPointSet.h"
#include "vtkPolyData.h"
#include "vtkPolyDataNormals.h"
#include "vtkSmoothPolyDataFilter.h"
#include "vtkTransform.h"
#include "vtkTransformPolyDataFilter.h"
#include <string>

#endif //_MeshEditorPluginPCH_H
